## capital_hub — Crownfall, the spawn-hub capital (2026-07-24). A STANDALONE
## 25-room authored city: a dense service heart, four compact faction wards,
## one northern overlook, and the southern gate approach. Dev-only for now —
## reached via the dev panel "Go To Capital" button (Story.chapter("capital")
## resolves this CHAPTER; game_world.switch_chapter allows it as a standalone).
##
## Fixed layout: every zone carries an authored "coord" + "exits", so
## game_world._prepare_rooms lays them out verbatim (no seeded spine). Authored
## room_scale makes social halls grand and single-purpose chambers intimate.
## All zones are "safe" (no packs). Exact landmarks and restrained district
## scenery replace inherited terrain scatter. NPCs use the ch2-hub data pattern;
## portal props leave for Story / Crucible / Depths, and civic interactables
## open the existing shop, gear, skills, social, mail, journal, records, vault,
## Codex, map, and daily-service screens.
## GENERATED by tools/content/gen_capital.py — edit the generator, not this file.
class_name CapitalHub

# The standalone world. Story.chapter("capital") returns this; it is kept OUT of
# CHAPTER_LIST so campaign machinery (chapter select, weekly rotation, act gating)
# never sees it — exactly like the endgame arenas.
const CHAPTER := {
	"name": "Crownfall",
	"sub": "A gathering city — services at the heart, four wards at the corners",
	"standalone": true,
	"loot_cap": "C",
	"start_quest": "",
	"final_boss": "",
	"start_pos": [1056, 624],
	"zones": [
	{"name": "Crown Plaza", "terrain": "ph_market", "type": "safe",
		"coord": [0, 0], "room_scale": 1.00, "exits": ["N", "S", "E", "W"], "enemies": [], "boss": "",
		"district": "heart", "mark": "★",
		"obstacles": ["bench2", "amphora"], "obstacle_count": 2,
		"decor": ["pebble", "banner_red"], "decor_count": 2, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_crown_fountain", "x": 1056, "y": 600, "clearance": 300}, {"name": "notice_board", "x": 1056, "y": 850, "clearance": 110}],
		"npcs": [
			{"sprite": "factor_imre", "x": 1400, "y": 650, "prompt": "E — Ask for directions", "convo": "cap_citizen"},
			{"sprite": "book", "x": 1056, "y": 850, "prompt": "E — View the city map", "action": "map", "hidden": true}],
	},
	{"name": "Wayfinder Sanctum", "terrain": "ph_hall", "type": "safe",
		"coord": [0, -1], "room_scale": 0.82, "exits": ["N", "S", "E", "W"], "enemies": [], "boss": "",
		"district": "civic", "mark": "◆",
		"obstacles": ["bench2", "amphora", "library_desk"], "obstacle_count": 2,
		"decor": ["pebble", "candle"], "decor_count": 2, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_portal_story", "x": 560, "y": 560, "clearance": 150}, {"name": "capital_portal_crucible", "x": 1056, "y": 560, "clearance": 160}, {"name": "capital_portal_depths", "x": 1552, "y": 560, "clearance": 145}],
		"npcs": [
			{"sprite": "void_rift", "x": 560, "y": 590, "prompt": "◆ The Story Gate", "action": "portal_story", "hidden": true},
			{"sprite": "void_monolith", "x": 1056, "y": 570, "prompt": "◆ The Crucible Gate", "action": "portal_crucible", "hidden": true},
			{"sprite": "void_obelisk", "x": 1552, "y": 590, "prompt": "◆ The Depths Gate", "action": "portal_depths", "hidden": true}],
	},
	{"name": "Artisans' Court", "terrain": "ph_castle", "type": "safe",
		"coord": [-1, -1], "room_scale": 0.88, "exits": ["S", "E", "W"], "enemies": [], "boss": "",
		"district": "craft", "mark": "",
		"obstacles": ["bench2", "amphora", "station_anvil_t1"], "obstacle_count": 2,
		"decor": ["pebble", "candle"], "decor_count": 2, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_ashfire_forge", "x": 610, "y": 585, "clearance": 270}, {"name": "capital_grand_archive", "x": 1500, "y": 585, "clearance": 235}],
		"npcs": [
			{"sprite": "smith_petra", "x": 660, "y": 690, "prompt": "E — Smith Petra", "convo": "cap_petra"},
			{"sprite": "archivist_lene", "x": 1450, "y": 690, "prompt": "E — Master Lapidary", "convo": "cap_lapidary"},
			{"sprite": "chest_gold", "x": 1056, "y": 800, "prompt": "E — Open your vault", "action": "vault"},
			{"sprite": "settings", "x": 610, "y": 520, "prompt": "E — Manage your gear", "action": "gear", "hidden": true}],
	},
	{"name": "The Grand Archive", "terrain": "ph_library", "type": "safe",
		"coord": [1, -1], "room_scale": 0.76, "exits": ["S", "E", "W"], "enemies": [], "boss": "",
		"district": "civic", "mark": "",
		"obstacles": ["bench2", "amphora", "library_desk"], "obstacle_count": 2,
		"decor": ["pebble", "candle"], "decor_count": 2, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_grand_archive", "x": 1056, "y": 585, "clearance": 285}],
		"npcs": [
			{"sprite": "book", "x": 620, "y": 760, "prompt": "E — Browse the Codex", "action": "codex", "hidden": true},
			{"sprite": "book", "x": 1056, "y": 760, "prompt": "E — Read your journal", "action": "journal", "hidden": true},
			{"sprite": "book", "x": 1492, "y": 760, "prompt": "E — Review your records", "action": "records", "hidden": true}],
	},
	{"name": "The Chartered Hall", "terrain": "ph_guildhall", "type": "safe",
		"coord": [-1, 0], "room_scale": 0.68, "exits": ["N", "S", "E"], "enemies": [], "boss": "",
		"district": "civic", "mark": "",
		"obstacles": ["bench2", "amphora", "library_desk"], "obstacle_count": 2,
		"decor": ["pebble", "candle"], "decor_count": 2, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_chartered_hall", "x": 1056, "y": 590, "clearance": 285}],
		"npcs": [
			{"sprite": "clerk_voss", "x": 1056, "y": 814, "prompt": "E — Open Play Together", "action": "guild"}],
	},
	{"name": "Crown Bazaar", "terrain": "ph_market", "type": "safe",
		"coord": [1, 0], "room_scale": 0.92, "exits": ["N", "S", "W"], "enemies": [], "boss": "",
		"district": "civic", "mark": "",
		"obstacles": ["bench2", "amphora", "library_desk"], "obstacle_count": 2,
		"decor": ["pebble", "candle"], "decor_count": 2, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_market_stall", "x": 620, "y": 600, "clearance": 215}, {"name": "capital_market_stall", "x": 1492, "y": 600, "clearance": 215}],
		"merchant": [1056, 560],
		"npcs": [
			{"sprite": "clerk_voss", "x": 720, "y": 790, "prompt": "E — Claim the daily alms", "action": "daily"},
			{"sprite": "mail", "x": 1390, "y": 790, "prompt": "E — Check your mailbox", "action": "mail", "hidden": true}],
	},
	{"name": "The Hearthworks", "terrain": "ph_kitchen", "type": "safe",
		"coord": [-1, 1], "room_scale": 0.78, "exits": ["N", "E", "W"], "enemies": [], "boss": "",
		"district": "craft", "mark": "",
		"obstacles": ["bench2", "amphora", "station_anvil_t1"], "obstacle_count": 2,
		"decor": ["pebble", "candle"], "decor_count": 2, "accents": [], "structures": [],
		"landmarks": [{"name": "great_hearth", "x": 620, "y": 560, "clearance": 175}, {"name": "brew_stand", "x": 1492, "y": 560, "clearance": 175}],
		"npcs": [
			{"sprite": "old_fenna", "x": 650, "y": 650, "prompt": "E — Old Fenna", "convo": "cap_fenna"},
			{"sprite": "apprentice_sorrel", "x": 1460, "y": 650, "prompt": "E — Apprentice Sorrel", "convo": "cap_sorrel"}],
	},
	{"name": "The Ashen Tankard", "terrain": "ph_kitchen", "type": "safe",
		"coord": [0, 1], "room_scale": 0.72, "exits": ["N", "S", "E", "W"], "enemies": [], "boss": "",
		"district": "civic", "mark": "",
		"obstacles": ["bench2", "amphora", "library_desk"], "obstacle_count": 2,
		"decor": ["pebble", "candle"], "decor_count": 2, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_ashen_tankard", "x": 1056, "y": 590, "clearance": 285}],
		"npcs": [
			{"sprite": "peddler_nix", "x": 1056, "y": 814, "prompt": "E — Tavern Keeper Nix", "convo": "cap_tankard"}],
	},
	{"name": "The Proving Grounds", "terrain": "ph_castle", "type": "safe",
		"coord": [1, 1], "room_scale": 0.90, "exits": ["N", "E", "W"], "enemies": [], "boss": "",
		"district": "civic", "mark": "",
		"obstacles": ["bench2", "amphora", "library_desk"], "obstacle_count": 2,
		"decor": ["pebble", "candle"], "decor_count": 2, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_proving_gate", "x": 1056, "y": 560, "clearance": 290}],
		"npcs": [
			{"sprite": "warden_corin", "x": 1056, "y": 800, "prompt": "E — Proving Marshal Corin", "convo": "cap_arena"},
			{"sprite": "skills", "x": 1056, "y": 535, "prompt": "E — Open your skill tree", "action": "skills", "hidden": true}],
	},
	{"name": "Crownwatch Rampart", "terrain": "ph_castle", "type": "safe",
		"coord": [0, -2], "room_scale": 0.68, "exits": ["S"], "enemies": [], "boss": "",
		"district": "outer", "mark": "",
		"obstacles": ["hideout_barrel", "hideout_kegs", "pillar"], "obstacle_count": 2,
		"decor": ["pebble", "crack"], "decor_count": 2, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_watchtower", "x": 1056, "y": 560, "clearance": 235}],
		"npcs": [
			{"sprite": "warden_palla", "x": 1056, "y": 814, "prompt": "E — Toll-Warden Palla", "convo": "cap_palla"}],
	},
	{"name": "Fangmoot Circle", "terrain": "ph_camp", "type": "safe",
		"coord": [-2, -1], "room_scale": 0.82, "exits": ["N", "E", "W"], "enemies": [], "boss": "",
		"district": "wild", "mark": "●",
		"obstacles": ["tree_green", "rock", "bush"], "obstacle_count": 3,
		"decor": ["grass", "flower", "pebble"], "decor_count": 3, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_wildfang_fangmoot", "x": 1056, "y": 570, "clearance": 285}],
		"npcs": [
			{"sprite": "callis", "x": 720, "y": 650, "prompt": "E — Warden Callis", "convo": "cap_callis"},
			{"sprite": "skald_ottar", "x": 1390, "y": 650, "prompt": "E — Skald Ottar", "convo": "cap_ottar"}],
	},
	{"name": "The Green Warren", "terrain": "ph_fae", "type": "safe",
		"coord": [-3, -1], "room_scale": 0.68, "exits": ["E"], "enemies": [], "boss": "",
		"district": "wild", "mark": "",
		"obstacles": ["tree_green", "rock", "bush"], "obstacle_count": 3,
		"decor": ["grass", "flower", "pebble"], "decor_count": 3, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_accord_longhouse", "x": 1056, "y": 590, "clearance": 300}],
		"npcs": [
			{"sprite": "npc_hunter", "x": 1056, "y": 814, "prompt": "E — The Old Hunter", "convo": "cap_hunter"}],
	},
	{"name": "Digger's Cut", "terrain": "ph_dungeon", "type": "safe",
		"coord": [-2, -2], "room_scale": 0.62, "exits": ["S"], "enemies": [], "boss": "",
		"district": "wild", "mark": "",
		"obstacles": ["tree_green", "rock", "bush"], "obstacle_count": 3,
		"decor": ["grass", "flower", "pebble"], "decor_count": 3, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_undercroft", "x": 1056, "y": 580, "clearance": 270}],
		"npcs": [
			{"sprite": "digger_haim", "x": 1056, "y": 814, "prompt": "E — Old Digger Haim", "convo": "cap_haim"}],
	},
	{"name": "The Rot-Chapel", "terrain": "ph_crypt", "type": "safe",
		"coord": [2, -1], "room_scale": 0.82, "exits": ["N", "E", "W"], "enemies": [], "boss": "",
		"district": "choir", "mark": "●",
		"obstacles": ["tombstone", "grave_cross", "pillar"], "obstacle_count": 2,
		"decor": ["grave_crack", "web", "pebble"], "decor_count": 2, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_rot_chapel", "x": 1056, "y": 590, "clearance": 290}],
		"npcs": [
			{"sprite": "cantor_ilse", "x": 720, "y": 650, "prompt": "E — Cantor Ilse", "convo": "cap_ilse"},
			{"sprite": "deacon_vela", "x": 1390, "y": 650, "prompt": "E — Deacon Vela", "convo": "cap_vela"}],
	},
	{"name": "The Waiting Hall", "terrain": "ph_crypt", "type": "safe",
		"coord": [3, -1], "room_scale": 0.62, "exits": ["W"], "enemies": [], "boss": "",
		"district": "choir", "mark": "",
		"obstacles": ["tombstone", "grave_cross", "pillar"], "obstacle_count": 2,
		"decor": ["grave_crack", "web", "pebble"], "decor_count": 2, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_undercroft", "x": 1056, "y": 590, "clearance": 260}],
		"npcs": [
			{"sprite": "brother_osk", "x": 720, "y": 650, "prompt": "E — Brother Osk", "convo": "cap_osk"},
			{"sprite": "sera", "x": 1390, "y": 650, "prompt": "E — Widow Sera", "convo": "cap_sera"}],
	},
	{"name": "Suli's Hospice", "terrain": "ph_garden", "type": "safe",
		"coord": [2, -2], "room_scale": 0.68, "exits": ["S"], "enemies": [], "boss": "",
		"district": "choir", "mark": "",
		"obstacles": ["tombstone", "grave_cross", "pillar"], "obstacle_count": 2,
		"decor": ["grave_crack", "web", "pebble"], "decor_count": 2, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_wellspring", "x": 1056, "y": 590, "clearance": 265}],
		"npcs": [
			{"sprite": "suli", "x": 1056, "y": 814, "prompt": "E — Gentle Suli", "convo": "cap_suli"}],
	},
	{"name": "Accord Commons", "terrain": "ph_hall", "type": "safe",
		"coord": [-2, 1], "room_scale": 0.82, "exits": ["S", "E", "W"], "enemies": [], "boss": "",
		"district": "accord", "mark": "●",
		"obstacles": ["garden_bench", "garden_urns", "amphora"], "obstacle_count": 2,
		"decor": ["grass", "flower", "pebble"], "decor_count": 3, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_accord_longhouse", "x": 1056, "y": 590, "clearance": 315}],
		"npcs": [
			{"sprite": "elder", "x": 720, "y": 650, "prompt": "E — Elder Maren", "convo": "cap_maren"},
			{"sprite": "tinker_osla", "x": 1390, "y": 650, "prompt": "E — Tinker Osla", "convo": "cap_osla"}],
	},
	{"name": "The Menders' Row", "terrain": "ph_garden", "type": "safe",
		"coord": [-3, 1], "room_scale": 0.68, "exits": ["E"], "enemies": [], "boss": "",
		"district": "accord", "mark": "●",
		"obstacles": ["garden_bench", "garden_urns", "amphora"], "obstacle_count": 2,
		"decor": ["grass", "flower", "pebble"], "decor_count": 3, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_wellspring", "x": 1056, "y": 590, "clearance": 260}],
		"npcs": [
			{"sprite": "herbalist_kesh", "x": 1056, "y": 814, "prompt": "E — Herbalist Kesh", "convo": "cap_kesh"}],
	},
	{"name": "The Wellspring", "terrain": "ph_garden", "type": "safe",
		"coord": [-2, 2], "room_scale": 0.68, "exits": ["N"], "enemies": [], "boss": "",
		"district": "accord", "mark": "",
		"obstacles": ["garden_bench", "garden_urns", "amphora"], "obstacle_count": 2,
		"decor": ["grass", "flower", "pebble"], "decor_count": 3, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_wellspring", "x": 1056, "y": 590, "clearance": 280}],
		"npcs": [
			{"sprite": "fisher_dov", "x": 1056, "y": 814, "prompt": "E — Fisher Dov", "convo": "cap_dov"}],
	},
	{"name": "The Sable Court", "terrain": "ph_castle", "type": "safe",
		"coord": [2, 1], "room_scale": 0.82, "exits": ["S", "E", "W"], "enemies": [], "boss": "",
		"district": "cinder", "mark": "●",
		"obstacles": ["pillar", "castle_bust", "bench2"], "obstacle_count": 2,
		"decor": ["candle", "pebble", "banner_red"], "decor_count": 2, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_sable_hall", "x": 1056, "y": 590, "clearance": 315}],
		"npcs": [
			{"sprite": "aldric", "x": 720, "y": 650, "prompt": "E — Ser Aldric", "convo": "cap_aldric"},
			{"sprite": "vessa", "x": 1390, "y": 650, "prompt": "E — Envoy Vessa", "convo": "cap_vessa"}],
	},
	{"name": "Compact Foundry", "terrain": "ph_castle", "type": "safe",
		"coord": [3, 1], "room_scale": 0.68, "exits": ["W"], "enemies": [], "boss": "",
		"district": "cinder", "mark": "",
		"obstacles": ["pillar", "castle_bust", "bench2"], "obstacle_count": 2,
		"decor": ["candle", "pebble", "banner_red"], "decor_count": 2, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_ashfire_forge", "x": 1056, "y": 590, "clearance": 285}],
		"npcs": [
			{"sprite": "overseer_brann", "x": 1056, "y": 814, "prompt": "E — Overseer Brann", "convo": "cap_brann"}],
	},
	{"name": "The Keeper's Bastion", "terrain": "ph_library", "type": "safe",
		"coord": [2, 2], "room_scale": 0.72, "exits": ["N"], "enemies": [], "boss": "",
		"district": "cinder", "mark": "",
		"obstacles": ["pillar", "castle_bust", "bench2"], "obstacle_count": 2,
		"decor": ["candle", "pebble", "banner_red"], "decor_count": 2, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_grand_archive", "x": 1056, "y": 590, "clearance": 285}],
		"npcs": [
			{"sprite": "keeper_vasse", "x": 720, "y": 650, "prompt": "E — Retired Keeper Vasse", "convo": "cap_vasse"},
			{"sprite": "commander_ashe", "x": 1390, "y": 650, "prompt": "E — Commander Ashe", "convo": "cap_ashe"}],
	},
	{"name": "Crown Causeway", "terrain": "ph_market", "type": "safe",
		"coord": [0, 2], "room_scale": 0.76, "exits": ["N", "S"], "enemies": [], "boss": "",
		"district": "approach", "mark": "",
		"obstacles": ["hideout_barrel", "hideout_kegs", "pillar"], "obstacle_count": 2,
		"decor": ["pebble", "banner_red"], "decor_count": 2, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_watchtower", "x": 580, "y": 560, "clearance": 180}, {"name": "capital_watchtower", "x": 1532, "y": 560, "clearance": 180}],
		"npcs": [
			{"sprite": "warden_sighne", "x": 1056, "y": 814, "prompt": "E — Warden Sighne", "convo": "cap_sighne"}],
	},
	{"name": "The Emberward Gate", "terrain": "ph_castle", "type": "safe",
		"coord": [0, 3], "room_scale": 0.90, "exits": ["N", "E"], "enemies": [], "boss": "",
		"district": "approach", "mark": "",
		"obstacles": ["hideout_barrel", "hideout_kegs", "pillar"], "obstacle_count": 2,
		"decor": ["pebble", "banner_red"], "decor_count": 2, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_emberward_gate", "x": 1056, "y": 560, "clearance": 280}],
		"npcs": [
			{"sprite": "warden_corin", "x": 1056, "y": 814, "prompt": "E — Gate Sergeant Corin", "convo": "cap_gate"}],
	},
	{"name": "Emberward Stables", "terrain": "ph_camp", "type": "safe",
		"coord": [1, 3], "room_scale": 0.62, "exits": ["W"], "enemies": [], "boss": "",
		"district": "approach", "mark": "",
		"obstacles": ["hideout_barrel", "hideout_kegs", "pillar"], "obstacle_count": 2,
		"decor": ["pebble", "banner_red"], "decor_count": 2, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_stables", "x": 1056, "y": 590, "clearance": 315}],
		"npcs": [
			{"sprite": "warden_palla", "x": 1056, "y": 814, "prompt": "E — Ask about the road", "convo": "cap_stables"}],
	},
	],
}

# One short line per named resident (the ch2-hub CONVOS pattern). Merged into
# Story.ALL_CONVOS via the CONTENT_MODULES registration.
const CONVOS := {
	"cap_citizen": {"start": "a", "nodes": {"a": {"who": "A Citizen", "text": "First visit? The Wayfinder gates are north. Your vault, forge, and lapidary share the northwest court; Codex east, bazaar southeast. The four faction wards begin at the corners. Meet your company back here when you're done.", "next": ""}}},
	"cap_petra": {"start": "a", "nodes": {"a": {"who": "Smith Petra", "text": "One court for one kit: blades and armour at my forge, stones at the lapidary opposite, personal vault between us. No more marching across Crownfall because one buckle and one gemstone answer to different roofs.", "next": ""}}},
	"cap_sorrel": {"start": "a", "nodes": {"a": {"who": "Apprentice Sorrel", "text": "Herbalist Kesh lets me mind the Alembic when she's at the Menders' Row. Don't touch the green one. ...You touched the green one.", "next": ""}}},
	"cap_fenna": {"start": "a", "nodes": {"a": {"who": "Old Fenna", "text": "Kitchen on this side, Alembic on that. Kesh's herbs become supper or medicine without crossing the square. Sit by the hearth if you're waiting on friends; someone always knows who just came through a gate.", "next": ""}}},
	"cap_arena": {"start": "a", "nodes": {"a": {"who": "Proving Marshal Corin", "text": "Crownfall's companies drill here before they take the northern gates. For live trials, use the Crucible arch in the Wayfinder Sanctum. For bragging, use the rail — everyone in the plaza can hear you from there.", "next": ""}}},
	"cap_lapidary": {"start": "a", "nodes": {"a": {"who": "Master Lapidary", "text": "Petra handles metal; I handle what lives inside it. Raw stones, synthesis, sockets, enchantment — all in this half of the court. Your vault chest is between our benches so nothing needs carrying through the streets.", "next": ""}}},
	"cap_tankard": {"start": "a", "nodes": {"a": {"who": "Tavern Keeper", "text": "The Ashen Tankard — warmth, rumour, a fire that behaves. The whole city drifts through after dark. First cup's on the house for a shard-bearer.", "next": ""}}},
	"cap_gate": {"start": "a", "nodes": {"a": {"who": "Gate Sergeant", "text": "The Emberward Gate. Portcullis stays up in peacetime; the wild stays out on its honour. You came in clean — most do.", "next": ""}}},
	"cap_sighne": {"start": "a", "nodes": {"a": {"who": "Warden Sighne", "text": "This causeway is the city's spine: gate south, plaza north, Tankard to the west and Proving Grounds east. I mark who comes and goes. You go a lot, by the look of that gear.", "next": ""}}},
	"cap_palla": {"start": "a", "nodes": {"a": {"who": "Toll-Warden Palla", "text": "Stamps, seals, the gate ledger. No toll for the crowned and shard-touched — the city's glad enough you came back breathing.", "next": ""}}},
	"cap_stables": {"start": "a", "nodes": {"a": {"who": "Stable Warden Palla", "text": "Mounts, messengers, and caravan tack stay in this little yard beside the gate — close to the road and out of the plaza. If you're leaving on foot, take the centre causeway and keep the watchfires to your right.", "next": ""}}},
	"cap_callis": {"start": "a", "nodes": {"a": {"who": "Warden Callis", "text": "The tribes hold this enclave by truce, not welcome. Honest work, then: survey what the Waking's made of the east, and bring us word. Daily, if you're able.", "next": ""}}},
	"cap_ottar": {"start": "a", "nodes": {"a": {"who": "Skald Ottar", "text": "A fire that never dies and a skald who never stops. Go do a thing worth singing — I'll trade you the doing for the song. Come back with a story.", "next": ""}}},
	"cap_hunter": {"start": "a", "nodes": {"a": {"who": "The Old Hunter", "text": "This green's transplanted wildwood — the city lets us keep a scrap of the world we came from. Sit. Watch the treeline. It watches back.", "next": ""}}},
	"cap_haim": {"start": "a", "nodes": {"a": {"who": "Old Digger Haim", "text": "Sank this shaft under the enclave, into the old city's bones. I know what's down there. Guiding costs — knowing's free: don't go alone.", "next": ""}}},
	"cap_ilse": {"start": "a", "nodes": {"a": {"who": "Cantor Ilse", "text": "The Choir does not bury its dead — rot is the land's honest truth, and the dead keep their own vigil here. Tend them with me. It's patient work. Daily work.", "next": ""}}},
	"cap_vela": {"start": "a", "nodes": {"a": {"who": "Deacon Vela", "text": "Quieter tasks than the Cantor's: recover a relic, carry a name north to the sleepers, witness a thing and return unbroken. The blight rewards the faithful.", "next": ""}}},
	"cap_osk": {"start": "a", "nodes": {"a": {"who": "Brother Osk", "text": "I tend the ones lying down to wait for the Waking. I was something else, before. Ask me nothing; the sleepers dislike questions.", "next": ""}}},
	"cap_suli": {"start": "a", "nodes": {"a": {"who": "Gentle Suli", "text": "Even a cold faith gets sick. I mend the Choir's living — the one warm corner of the enclave. You look whole. Stay that way out there.", "next": ""}}},
	"cap_sera": {"start": "a", "nodes": {"a": {"who": "Widow Sera", "text": "I keep the Sexton's Gate down into the undercroft, among the dead. I decide who goes. I mostly say no. ...You've the look of a yes.", "next": ""}}},
	"cap_maren": {"start": "a", "nodes": {"a": {"who": "Elder Maren", "text": "So — the shards still choosing, and the factions still counting. The Accord holds this ward and half this city's conscience. There's honest work daily, if you want it. Sit; the fire doesn't bite.", "next": ""}}},
	"cap_kesh": {"start": "a", "nodes": {"a": {"who": "Herbalist Kesh", "text": "The Menders' Row — cures for the ward, reagents for the Alembic. I set the day's gathering. Bring back the right leaves and no one dies of the wrong ones.", "next": ""}}},
	"cap_osla": {"start": "a", "nodes": {"a": {"who": "Tinker Osla", "text": "Osla's yard — half-mended things and honest barter. There — seated. You've a strong shoulder for someone armed to the teeth. Flame keep you.", "next": ""}}},
	"cap_dov": {"start": "a", "nodes": {"a": {"who": "Fisher Dov", "text": "Still fish the cistern-water, if you can believe it. Ansa watches a tide that isn't there and swears it'll come back. Maybe it will. Odd city, this.", "next": ""}}},
	"cap_aldric": {"start": "a", "nodes": {"a": {"who": "Ser Aldric", "text": "The Cinderborn keep the forms of a court that lost its crown. I keep its sword arm. There's work in the old key — recover, restore, avenge — for a crown that might yet find a head. Daily, if you've the stomach.", "next": ""}}},
	"cap_vessa": {"start": "a", "nodes": {"a": {"who": "Envoy Vessa", "text": "Work with us and be paid, protected, and remembered. I've a commission most days — a courier run, a quiet errand, imperial paper with teeth. First one's waiting.", "next": ""}}},
	"cap_brann": {"start": "a", "nodes": {"a": {"who": "Overseer Brann", "text": "Here's the honest ledger: the Compact reopened these foundries, best ore two years running. The Forge upstairs eats what we dig. Good trade, if you can haul.", "next": ""}}},
	"cap_vasse": {"start": "a", "nodes": {"a": {"who": "Retired Keeper Vasse", "text": "Pre-Vargoth history, all of it — the Cinderborn's whole claim, written in old ink. A crown is a thing that can be re-forged, if you read the right page. I guard the page.", "next": ""}}},
	"cap_ashe": {"start": "a", "nodes": {"a": {"who": "Warden-Commander Ashe", "text": "This bastion keeps both the old rolls and the soldiers who still answer them. Vasse guards the memory; I drill the line. Read if you came for history. Fall in if you came to make it.", "next": ""}}},
}


## Merge + integrity selftest: the world resolves, every zone is safe, scaled,
## furnished around a landmark, and has an interaction; NPC refs are wired.
static func selftest(_game: Node2D) -> String:
	var ch: Dictionary = Story.chapter("capital")
	if ch.get("zones", []).size() != 25:
		return "capital: expected 25 zones, got %d" % ch.get("zones", []).size()
	var coords := {}
	var known_actions := ["codex", "daily", "gear", "guild", "journal", "mail", "map", "portal_crucible", "portal_depths", "portal_story", "records", "skills", "vault"]
	for z in ch["zones"]:
		if z.get("type", "") != "safe":
			return "capital: zone %s is not safe" % z.get("name", "?")
		if not Terrains.DATA.has(String(z.get("terrain", ""))):
			return "capital: zone %s has unknown terrain %s" % [z.get("name","?"), z.get("terrain","")]
		var room_scale: float = float(z.get("room_scale", 1.0))
		if room_scale < 0.55 or room_scale > 1.0:
			return "capital: zone %s has invalid room_scale %.2f" % [z.get("name","?"), room_scale]
		if z.get("landmarks", []).is_empty():
			return "capital: zone %s has no authored landmark" % z.get("name", "?")
		if z.get("npcs", []).is_empty() and not z.has("merchant"):
			return "capital: zone %s has no interaction" % z.get("name", "?")
		var c: Array = z.get("coord", [])
		var key := "%d,%d" % [int(c[0]), int(c[1])]
		if coords.has(key):
			return "capital: duplicate coord %s" % key
		coords[key] = true
		for npc in z.get("npcs", []):
			if npc.has("convo") and not Story.ALL_CONVOS.has(String(npc["convo"])):
				return "capital: NPC convo %s not registered" % npc["convo"]
			if npc.has("action") and String(npc["action"]) not in known_actions:
				return "capital: NPC action %s is not handled" % npc["action"]
			if Art.tex(String(npc["sprite"])) == null:
				return "capital: NPC sprite %s missing" % npc["sprite"]
	return ""
