class_name Game extends "res://scripts/game_flow.gd"
## GAME, layer 4 of 4 — boot (_ready, class select, save loading) and
## the per-frame driver. See game_base.gd for the chain layout.

# The transport autoload's SCRIPT, for enums/consts only — the bare
# `NetworkManager` global doesn't exist under check_compile (MP-05).
const NetManager := preload("res://scripts/net/net_manager.gd")

# --- MP session entry (dev-facing, MP-07; MP-08 builds the real lobby UI
# on these same seams). Layer-local state: only the boot flow reads them.
# The net test sets them directly before add_child; the CLI parse in
# _ready fills them from the user args.
var mp_host := false        # --mp-host[=ip:port]: host while playing normally
var mp_host_code := ""      # optional listen override (default 127.0.0.1:9999)
var mp_join_code := ""      # --mp-join=<code>: skip the title flow, join + handshake
var mp_cls := "warrior"     # --mp-cls=<class>: the joiner's dev character class
# --- DEDICATED server boot (MMO step A; `dedicated` itself lives in
# game_base — cross-layer code gates on it). Layer-local: boot flow only.
var server_code := ""       # --server[=port|ip:port]: listen address
var server_chapter := "ch1" # --chapter=<id>: fresh-world chapter pick
var server_fresh := false   # --fresh: ignore any persisted world file
var _server_save_t := 0.0   # periodic world-save cadence (MMO step B)
const SERVER_SAVE_EVERY := 60.0  # s between periodic world writes
const SERVER_EVENT_SPAN := [5.0, 8.0]  # terrain-event re-arm span (solo reads
                                       # the room's own event_t; the server
                                       # shares one timer across rooms)


## Filenames in an override asset dir (assets/<dir>, e.g. "sounds"/"music").
## Editor/source scans the folder live, so dropping in a file just works.
## An exported build can't enumerate imported audio (it's remapped inside
## the .pck, not a loose file), so it reads assets/asset_manifest.json —
## baked into the pack by the export include_filter and regenerated by
## tools/gen_asset_manifest.py before each export.
func _override_files(dir: String) -> PackedStringArray:
	if OS.has_feature("template"):  # exported build
		var mpath := "res://assets/asset_manifest.json"
		if not FileAccess.file_exists(mpath):
			return PackedStringArray()
		var data: Variant = JSON.parse_string(FileAccess.get_file_as_string(mpath))
		var out := PackedStringArray()
		if data is Dictionary and data.has(dir):
			for f in data[dir]:
				out.append(String(f))
		return out
	var da := DirAccess.open("res://assets/" + dir)
	return da.get_files() if da else PackedStringArray()


func _ready() -> void:
	loot_rng.randomize()
	load_binds()
	Story.load_content()  # merge content modules before anything reads them
	dev_mode = "--dev" in OS.get_cmdline_user_args()
	# MP session flags (MP-07 dev entry — see _start_flow).
	for arg in OS.get_cmdline_user_args():
		var s := str(arg)
		if s == "--mp-host":
			mp_host = true
		elif s.begins_with("--mp-host="):
			mp_host = true
			mp_host_code = s.get_slice("=", 1)
		elif s.begins_with("--mp-join="):
			mp_join_code = s.get_slice("=", 1)
		elif s.begins_with("--mp-cls="):
			mp_cls = s.get_slice("=", 1)
		elif s == "--server" or s.begins_with("--server="):
			# DEDICATED (MMO step A): headless world authority, no local
			# player. `--server=48300` or `--server=ip:port`; default port 9999.
			dedicated = true
			var v := s.get_slice("=", 1) if s.contains("=") else ""
			if v == "":
				server_code = "0.0.0.0:%d" % NetManager.DEFAULT_PORT
			elif v.contains(":"):
				server_code = v
			else:
				server_code = "0.0.0.0:%d" % int(v)
		elif s.begins_with("--chapter="):
			server_chapter = s.get_slice("=", 1)
		elif s == "--fresh":
			server_fresh = true
	# Hand the session bridge its game: net_session.gd (a child of the
	# NetworkManager autoload) owns the join handshake + movement sync.
	var net_session: Node = get_node_or_null("/root/NetworkManager/Session")
	if net_session != null:
		net_session.game = self
	zones = Story.chapter(chapter_id)["zones"]
	zone_count = zones.size()
	for zone in zones:
		terrain_by_zone.append(zone.get("terrain", "village"))
	_prepare_rooms()

	sounds = Sfx.build_all()
	# Sound overrides: any assets/sounds/<name>.wav or .ogg replaces the
	# synthesized effect of the same name (same idea as sprites).
	for file in _override_files("sounds"):
		if not (file.ends_with(".wav") or file.ends_with(".ogg") or file.ends_with(".mp3")):
			continue
		# Loaded via the resource system so overrides survive an export:
		# a packed .pck has no loose files for load_from_file to reach.
		var res_path := "res://assets/sounds/" + file
		if not ResourceLoader.exists(res_path):
			continue
		var snd := load(res_path) as AudioStream
		if snd:
			sounds[file.get_basename()] = snd
	for i in 10:
		var sp := AudioStreamPlayer.new()
		sp.volume_db = -8.0
		add_child(sp)
		sound_pool.append(sp)

	# Background music: looping procedural chiptune, one per zone + boss.
	music_tracks = Music.build_all()
	# Music overrides: assets/music/<track>.ogg/.mp3/.wav replaces the
	# composed track of the same name, looped — same idea as sprites/sfx.
	for file in _override_files("music"):
		if not (file.ends_with(".ogg") or file.ends_with(".mp3") or file.ends_with(".wav")):
			continue
		# load() so music overrides apply in exported builds too.
		var res_path := "res://assets/music/" + file
		if not ResourceLoader.exists(res_path):
			continue
		var tune: Dictionary = MUSIC_TUNE.get(file.get_basename(), {})
		var track := load(res_path)
		if track is AudioStreamOggVorbis:
			var ogg := track as AudioStreamOggVorbis
			ogg.loop = true
			ogg.loop_offset = float(tune.get("start", 0.0))
			music_tracks[file.get_basename()] = ogg
		elif track is AudioStreamMP3:
			var mp3 := track as AudioStreamMP3
			mp3.loop = true
			mp3.loop_offset = float(tune.get("start", 0.0))
			music_tracks[file.get_basename()] = mp3
		elif track is AudioStreamWAV:
			var wav := track as AudioStreamWAV
			wav.loop_mode = AudioStreamWAV.LOOP_FORWARD
			wav.loop_end = wav.data.size() / (4 if wav.stereo else 2)
			music_tracks[file.get_basename()] = wav
	music_player = AudioStreamPlayer.new()
	music_player.volume_db = -16.0
	# Music survives the pause: boot menus (cover/roster) run with the
	# tree paused, and the pause menu shouldn't strangle the track.
	music_player.process_mode = Node.PROCESS_MODE_ALWAYS
	add_child(music_player)
	amb_player = AudioStreamPlayer.new()
	amb_player.volume_db = AMB_DB
	amb_player.process_mode = Node.PROCESS_MODE_ALWAYS
	add_child(amb_player)
	load_settings()
	apply_audio_settings()
	apply_display_settings()
	refresh_touch_mode()

	ambient = CanvasModulate.new()
	ambient.color = Terrains.get_terrain(terrain_by_zone[0])["tint"]
	add_child(ambient)

	# 2D glow (needs Forward+ and viewport/hdr_2d, set in project.godot):
	# additive FX stacks (spell impacts, ult flashes, loot beams) push past
	# 1.0 brightness and bloom; ordinary sprites sit under the threshold.
	glow_env = WorldEnvironment.new()
	var env := Environment.new()
	env.background_mode = Environment.BG_CANVAS
	env.glow_enabled = true
	env.glow_blend_mode = Environment.GLOW_BLEND_MODE_ADDITIVE
	env.glow_hdr_threshold = 1.1
	env.glow_intensity = 0.55
	env.glow_bloom = 0.0
	env.set_glow_level(1, 0.5)
	env.set_glow_level(3, 1.0)
	env.set_glow_level(5, 0.6)
	glow_env.environment = env
	add_child(glow_env)

	world = Node2D.new()
	world.y_sort_enabled = true  # world children sort with the player
	add_child(world)
	_build_door_seals()

	# DEDICATED: no local player, ever — the whole point of step A. Every
	# lingering "there is always a player on this machine" assumption gates
	# on has_local_player() / the dedicated _process branch below.
	if not dedicated:
		player = Player.new()
		player.game = self
		player.global_position = _start_pos()
		add_child(player)

	reticle = Sprite2D.new()
	reticle.texture = Art.tex("reticle")
	reticle.scale = Vector2(2, 2)
	reticle.z_index = 25
	reticle.visible = false
	add_child(reticle)
	# Target's level floats above the lock-on brackets.
	reticle_label = Label.new()
	reticle_label.position = Vector2(-30, -24)
	reticle_label.size = Vector2(60, 14)
	reticle_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	reticle_label.scale = Vector2(0.5, 0.5)
	reticle_label.add_theme_font_size_override("font_size", 20)
	reticle_label.add_theme_color_override("font_outline_color", Color(0, 0, 0))
	reticle_label.add_theme_constant_override("outline_size", 6)
	reticle.add_child(reticle_label)

	camera = Camera2D.new()
	camera.position_smoothing_enabled = true
	camera.position_smoothing_speed = 8.0
	camera.zoom = Vector2(1.12, 1.12)  # slightly closer = chunkier pixels
	if dedicated:
		add_child(camera)  # no hero to ride; _enter_room still sets limits
	else:
		player.add_child(camera)
	camera.make_current()

	hud = Hud.new()
	hud.game = self
	add_child(hud)
	_apply_touch_mode()
	refresh_quest()

	menus = Menus.new()
	menus.game = self
	add_child(menus)

	# Build and enter the starting room (the rest of the graph is lazy).
	_enter_room(0 if dedicated else room_at_pos(player.global_position))

	# First: pick a class. Then the story begins.
	call_deferred("_start_flow")

func _start_flow() -> void:
	if dedicated:
		_server_boot()   # pure authority: no title flow, no class pick
		return
	if mp_join_code != "":
		_mp_join_boot()  # joiner: no title flow — the world comes from the host
		return
	if mp_host:
		_mp_host_boot()  # host: start listening, then play normally below
	if no_saves:
		menus.open_chapter_select()  # autotest: straight to the pick
	else:
		# Real players always land on the cover, saves or none:
		# cover -> character roster -> (new hero) chapter + class select.
		menus.open_title()


## --mp-host: listen on ENET_DIRECT (dev default 127.0.0.1:9999) while
## the normal title flow proceeds. Guests are ADMITTED immediately (the
## MP-05 version gate), but the world snapshot only goes out once a
## character is picked/loaded — net_session's handshake waits for
## play_started. Fire-and-forget coroutine.
func _mp_host_boot() -> void:
	var net: Node = get_node("/root/NetworkManager")
	var err: Error = await net.host(NetManager.Mode.ENET_DIRECT, mp_host_code)
	print("[mp] host session: %s — code %s" % [error_string(err), str(net.session_code)])


## --mp-join=<code>: the wave-4 dev joiner. Skips the title flow — a dev
## character (mp_cls, level 1) rides in; the host's snapshot (chapter,
## seed, flags) arrives via net_session.gd after admission and rebuilds
## the world locally (MULTIPLAYER.md §4.1 row 1). Real players go through
## the lobby instead (MP-08, ui/lobby.gd) — it puts their roster SLOT in
## local_char and the snapshot handler loads that save's character.
func _mp_join_boot() -> void:
	var sess: Node = get_node("/root/NetworkManager/Session")
	sess.local_char = {"cls": mp_cls, "level": 1}
	var net: Node = get_node("/root/NetworkManager")
	var err: Error = await net.join(mp_join_code)
	print("[mp] join %s: %s" % [mp_join_code, error_string(err)])


## --server (MMO step A): boot the DEDICATED world authority. Listen first
## (guests may knock while the world builds — the snapshot handshake waits
## on play_started), then stand the world up: the persisted one if a
## server_world.json exists (MMO step B), else a fresh roll of --chapter.
## The lobby stays open forever — drop-in joins are the point.
func _server_boot() -> void:
	var net: Node = get_node("/root/NetworkManager")
	var err: Error = await net.host(NetManager.Mode.ENET_DIRECT, server_code,
		NetManager.MAX_SERVER_GUESTS)
	if err != OK:
		print("[server] FATAL: cannot listen on %s (%s)" % [server_code, error_string(err)])
		get_tree().quit(1)
		return
	var data := SaveGame.read_server_world()
	if server_fresh or data.is_empty():
		wander_seed = randi() % 1000000
		reset_run_stats()
		switch_chapter(server_chapter, true)
		print("[server] fresh world: %s, seed %d" % [chapter_id, wander_seed])
	else:
		# load_save's contract: seed first, rebuild, then apply the rest.
		wander_seed = int(SaveGame.world_of(data).get("wander_seed", 0))
		switch_chapter(String(data.get("chapter", server_chapter)), true)
		SaveGame.apply_server_world(self, data)
		print("[server] restored world: %s, seed %d, %d rooms cleared, %d bosses down"
			% [chapter_id, wander_seed, cleared.size(), boss_done.size()])
	state = ST_PLAYING
	play_started = true
	autosave()  # a fresh world persists its seed immediately (step B)
	print("[server] world authority up — listening on %s (%d seats)"
		% [str(net.session_code), NetManager.MAX_SERVER_GUESTS])


## DEDICATED per-frame driver: the sim-relevant subset of _process below,
## with no local player to read. Presentation (HUD binding, reticle, boss
## bar, camera shake, footsteps, NPC chatter) is skipped whole — guests
## each render their own.
func _server_process(delta: float) -> void:
	# The sim gate follows every CONNECTED player; rooms a guest reached
	# first build + arm here (same pair the listen host runs per frame).
	_refresh_active_rooms()
	_host_ensure_active_rooms()
	if state != ST_PLAYING:
		return
	run_time += delta
	# Fight-report bookkeeping (boss records/TTK stay meaningful on a
	# server): first blood engages via take_damage, the clock rides here.
	if fight_active:
		for b in _live_bosses():
			fight_track(b)
		fight_time += delta
	# Terrain events fire in every OCCUPIED eventful room, anchored on a
	# player standing in it (solo anchors on the local player + cur_room).
	terrain_event_t -= delta
	if terrain_event_t <= 0.0:
		terrain_event_t = randf_range(SERVER_EVENT_SPAN[0], SERVER_EVENT_SPAN[1])
		for r in active_rooms:
			var zi := int(r)
			if zi < 0 or zi >= zone_count:
				continue
			var ev := String(Terrains.get_terrain(terrain_by_zone[zi]).get("event", ""))
			if ev == "":
				continue
			var anchors := players_in_room(zi)
			if not anchors.is_empty():
				run_terrain_event(ev, zi, anchors[randi() % anchors.size()])
	# Hazard patches tick enemies (and drift/expire) exactly like solo;
	# each guest's own machine ticks its own player (§4.1 hazards row).
	hazard_tick -= delta
	if hazard_tick <= 0.0:
		hazard_tick = 0.4
		_apply_hazards()
	if gust_t > 0.0:
		gust_t -= delta
		if gust_t <= 0.0:
			gust_vec = Vector2.ZERO
	# Periodic world persistence (step B): autosave() routes to
	# write_server_world while dedicated. Event saves (room clears, boss
	# kills, story flags) ride the existing autosave call sites.
	_server_save_t += delta
	if _server_save_t >= SERVER_SAVE_EVERY:
		_server_save_t = 0.0
		autosave()

func on_class_chosen(id: String) -> void:
	player.set_class(id)
	wander_seed = randi() % 1000000  # seeds this character's layout + rolled rooms
	reset_run_stats()  # the results card starts counting from here
	switch_chapter(chapter_id, true)  # lay out THIS run's world from the fresh seed
	if not no_saves:
		save_slot = SaveGame.next_free_slot()
	request_pause(false)
	# The class-select menu hid the HUD on the way in — and the opening's
	# dialogue box and cutscene stage are its CHILDREN, so it must come back
	# BEFORE the convo below or the whole opening plays invisibly (a "frozen"
	# game to the player). The cutscene's full-screen stage covers the
	# gameplay bars, so nothing gameplay-shaped leaks into the cinematic.
	hud.visible = true
	var begin := func() -> void:
		play_started = true
		set_music(Terrains.get_terrain(terrain_by_zone[cur_room]).get("music", "village"))
		hud.flash_title(zones[cur_room]["name"], String(Story.chapter(chapter_id)["name"]))
		autosave()
	if Story.ALL_CONVOS.has("open_" + id):
		# Class openings replace the generic intro: a staged cinematic
		# plays under the words (cues in Story.CONVOS), and a choice
		# moves Resonance before Maren ever appears.
		set_flag("opened_" + id)
		cutscene = Cutscene.new(self)
		hud.add_child(cutscene)
		# Above the gameplay HUD (bars/quest/abilities), under the words.
		hud.move_child(cutscene, hud.dialogue_box.get_index())
		run_convo_id("open_" + id, func() -> void:
			if cutscene:
				var cs := cutscene
				cutscene = null
				cs.finish(begin)
			else:
				begin.call())
	else:
		hud.dialogue(Story.ALL_BEATS["intro"], begin)

## Resume a saved character: restore the player + story flags onto the
## freshly built world, then skip straight into play (no intro).
func load_save(slot: int) -> void:
	var data := SaveGame.read(slot)
	if data.is_empty():
		return
	save_slot = slot
	guest_world = false  # resuming OUR world: full autosaves again (MP-08)
	# The layout is a pure function of wander_seed: restore the seed
	# FIRST, then force-rebuild so the world matches the saved one.
	wander_seed = int(SaveGame.world_of(data).get("wander_seed", 0))
	switch_chapter(String(data.get("chapter", "ch1")), true)
	SaveGame.apply(self, data)
	request_pause(false)
	play_started = true
	hud.visible = true  # the load menu hid it on the way in
	set_music(Terrains.get_terrain(terrain_by_zone[cur_room]).get("music", "village"))
	hud.flash_title(zones[cur_room]["name"], "The tale continues")

## Rebuild the world state a save implies: mark dead bosses' rooms
## resolved and re-check every built gate against the restored flags
## and kills. (Unbuilt rooms evaluate their locks at build time.)
func reconcile_after_load() -> void:
	if talked_to_elder and not get_flag("met_elder", false):
		set_flag("met_elder")  # pre-graph saves stored only the bool
	for zi in zone_count:
		var kind: String = zones[zi].get("boss", "")
		if kind != "" and boss_done.get(kind, false):
			boss_spawned[zi] = true
			zone_alive[zi] = 0
			cleared[zi] = true
	_recheck_gates()
	refresh_quest()

# --- dev review controls (dev_mode ONLY): slow-mo + camera zoom, for
# eyeballing animations in-engine. Gated so a shipped build never sees them.
#   \  cycles game speed 1x -> 0.5 -> 0.25 -> 0.1 -> 1x
#   =  hold to zoom IN,  -  hold to zoom OUT
const _DEV_SLOWMO := [1.0, 0.5, 0.25, 0.1]
var _dev_slowmo_i := 0
var _dev_slow_held := false

func _dev_review_input(delta: float) -> void:
	if not dev_mode:
		return
	var slow := Input.is_key_pressed(KEY_BACKSLASH)
	if slow and not _dev_slow_held:
		_dev_slowmo_i = (_dev_slowmo_i + 1) % _DEV_SLOWMO.size()
		Engine.time_scale = _DEV_SLOWMO[_dev_slowmo_i]
		if is_instance_valid(player):
			spawn_text(player.global_position + Vector2(0, -74),
				"TIME x%.2f" % Engine.time_scale, Color(0.6, 0.9, 1.0))
	_dev_slow_held = slow
	if camera:
		# unscale by time_scale so zoom feels the same however slow the game is
		var step := 1.6 * (delta / maxf(0.0001, Engine.time_scale))
		var z: float = camera.zoom.x
		if Input.is_key_pressed(KEY_EQUAL):
			z += step
		elif Input.is_key_pressed(KEY_MINUS):
			z -= step
		camera.zoom = Vector2.ONE * clampf(z, 0.4, 4.0)


## Mount or remove the on-screen touch controls to match touch_mode. Called at boot
## and whenever the control-scheme setting is toggled, so it flips live on desktop.
func _apply_touch_mode() -> void:
	if touch_mode and _touch_hud == null:
		_touch_hud = TouchHud.new()
		_touch_hud.game = self
		add_child(_touch_hud)   # TouchHud._ready hides the keyboard ability bar
	elif not touch_mode and _touch_hud != null:
		_touch_hud.queue_free()
		_touch_hud = null
		if hud:
			hud.set_touch_mode(false)   # restore the keyboard ability bar


## Settings toggle: flip touch controls on/off, persist, and apply live.
func set_touch_controls(on: bool) -> void:
	settings["touch_controls"] = on
	save_settings()
	refresh_touch_mode()
	_apply_touch_mode()


func _unhandled_input(event: InputEvent) -> void:
	# Touch-only tap-to-talk: a phone has no E key, so tapping an NPC you're standing
	# next to fires its convo/desk — same range + action as the keyboard path below
	# (~L484). Only UNCONSUMED taps reach here, so the touch HUD's joystick/ability
	# arc never trigger it; desktop keeps press-E (touch_mode is false there).
	# choices_active is its OWN overlay flag: dialogue_active drops before
	# dialogue_choice raises it (hud.gd) — without the check, a stray tap near
	# the NPC re-fires their convo UNDER a pending decision in a session
	# (solo the pause blocks this handler; §5.4 skips the pause online).
	if not touch_mode or state != ST_PLAYING or hud.dialogue_active \
			or hud.choices_active or menus.is_open():
		return
	if ((event is InputEventScreenTouch and event.pressed) or (event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_LEFT and event.pressed)) and talk_cd <= 0.0:
		var world: Vector2 = get_viewport().canvas_transform.affine_inverse() * event.position
		for entry in interactables:
			if not is_instance_valid(entry["node"]):
				continue
			var np: Vector2 = entry["node"].position
			if player.global_position.distance_to(np) < 80.0 and world.distance_to(np) < 90.0:
				talk_cd = 0.6
				_face_interactable_to_player(entry)
				entry["action"].call()
				break


## Directional NPC bodies turn toward the local player when spoken to. Only
## sprites shipping `<name>_anim_<dir>.png` opt in; existing static NPC art
## remains on its original, single-facing path.
func _face_interactable_to_player(entry: Dictionary) -> void:
	var dirs: Dictionary = entry.get("dir_anims", {})
	if dirs.is_empty():
		return
	var npc := entry.get("node") as Node2D
	var spr := entry.get("sprite") as Sprite2D
	if not is_instance_valid(npc) or not is_instance_valid(spr):
		return
	var face: String = Art.dir8_suffix(player.global_position - npc.global_position)
	var info: Dictionary = dirs.get(face, {})
	if info.is_empty():
		return
	active_facing_interactable = entry
	var frames: int = int(info.get("frames", 1))
	spr.texture = info["tex"]
	spr.hframes = frames
	spr.frame = 0
	var body_target: float = float(entry.get("body_target", 0.0))
	if body_target > 0.0:
		var legacy_scale := Art.scale_for(spr.texture,
			float(entry.get("render_scale", Balance.NPC_RENDER_SCALE))
				* float(entry.get("size_var", 1.0)), frames)
		spr.scale = Art.scale_for_alpha_height(spr.texture,
			body_target * Balance.CHAR_RENDER_SCALE
				* float(entry.get("size_var", 1.0)), frames)
		spr.position.y = Art.alpha_feet_offset(spr.texture, legacy_scale.y, frames) \
			- Art.alpha_feet_offset(spr.texture, spr.scale.y, frames)
	else:
		spr.scale = Art.scale_for(spr.texture,
			float(entry.get("render_scale", Balance.NPC_RENDER_SCALE))
				* float(entry.get("size_var", 1.0)), frames)


## A conversation/shop owns the temporary facing state. Once its overlay has
## gone, restore the original south-facing idle instead of leaving the NPC
## staring at the last player who spoke to them.
func _restore_interactable_rest_pose() -> void:
	if active_facing_interactable.is_empty():
		return
	var entry := active_facing_interactable
	active_facing_interactable = {}
	var spr := entry.get("sprite") as Sprite2D
	if not is_instance_valid(spr):
		return
	var rest_tex := entry.get("rest_tex") as Texture2D
	if rest_tex == null:
		return
	spr.texture = rest_tex
	spr.hframes = int(entry.get("rest_frames", 1))
	spr.frame = int(entry.get("rest_frame", 0))
	spr.scale = entry.get("rest_scale", Vector2.ONE) as Vector2
	spr.position = entry.get("rest_pos", Vector2.ZERO) as Vector2


func _process(delta: float) -> void:
	if dedicated:
		_server_process(delta)
		return
	talk_cd = maxf(0.0, talk_cd - delta)
	_dev_review_input(delta)   # dev_mode: slow-mo (\) + zoom (=/-)
	if not active_facing_interactable.is_empty() and not hud.dialogue_active \
			and not hud.choices_active and not menus.is_open():
		_restore_interactable_rest_pose()
	if hud.dialogue_active or hud.choices_active or menus.is_open():
		talk_cd = 0.4
	if play_started and state == ST_PLAYING:
		run_time += delta  # chapter run clock (results card; pauses pause it)
		if endgame_active and endgame != null:
			endgame.tick(delta)  # endgame arena: watch for a Depths wave clearing
	refresh_ambience()  # ambient bed tracks the room's terrain (cheap no-op)
	track_footprints()  # snow remembers your steps (no-op off snow)
	tick_footsteps(delta)  # and every step SOUNDS (plate classes clank)

	# HUD, reticle and boss bar are PER-CLIENT presentation (MULTIPLAYER.md
	# §5.6): they bind to local_player — the player on THIS screen. Solo:
	# local_player == player, pixel-identical.
	hud.update_stats(local_player)

	# Reticle over the enemy your AIMED attacks would hit — the facing-gated
	# target, or the hard-locked one (orange). Hides when nothing is on your
	# side, which is itself the cue to turn and face a foe.
	var target := local_player.aim_focus()
	if target and not local_player.dead:
		reticle.visible = true
		reticle.global_position = target.global_position
		reticle.modulate = Color(1.0, 0.45, 0.2) if target == local_player.locked_target else Color(1, 1, 1)
		reticle_label.text = "Lv %d" % target.level
		# Color the level by threat vs your own level.
		var diff := target.level - local_player.level
		reticle_label.add_theme_color_override("font_color",
			Color(1, 0.35, 0.3) if diff >= 3 else (Color(1, 0.85, 0.4) if diff >= 0 else Color(0.6, 1, 0.6)))
	else:
		reticle.visible = false

	# The boss bar follows your TARGET: the locked/aimed boss if any,
	# else the first live one (endgame brawls run up to 5 at once).
	var live_bosses := _live_bosses()
	if not live_bosses.is_empty():
		var shown: Boss = local_player.locked_target as Boss
		if shown == null or not is_instance_valid(shown) or shown.dying:
			shown = target as Boss  # the auto-aim pick from above
		if shown == null or not live_bosses.has(shown):
			shown = live_bosses[0] if current_boss == null or not live_bosses.has(current_boss) else current_boss
		if shown != current_boss:
			current_boss = shown
			hud.show_boss_bar(shown.display_name)
		hud.update_boss_bar(current_boss.hp / current_boss.max_hp)
		# Fight-report bookkeeping: our first blood engages the clock
		# (a boss's first hit engages via take_damage); brawl
		# reinforcements join the HP pool the frame they appear.
		if fight_active:
			for b in live_bosses:
				fight_track(b)
			fight_time += delta
		else:
			for b in live_bosses:
				if b.hp < b.max_hp - 0.5:
					fight_engage()
					break

	# Room transitions: walking through a doorway moves you next door.
	# (Aggro is per-pack now — entering a room wakes nobody by itself.)
	var zi := room_at_pos(player.global_position)
	if zi == -1:
		# Physics glitch outside the graph: snap back into the room.
		var rr := play_rect(clampi(cur_room, 0, zone_count - 1))
		player.global_position.x = clampf(player.global_position.x, rr.position.x + 52.0, rr.end.x - 52.0)
		player.global_position.y = clampf(player.global_position.y, rr.position.y + 62.0, rr.end.y - 62.0)
		zi = cur_room
	elif zi != cur_room and state == ST_PLAYING:
		if _room_hot(cur_room):
			# Locked in: a HOT room seals every exit until it's purged (or
			# the boss falls). The pulsing seal glow is feedback; THIS is
			# the wall — the seal body sits a step outside the cell and
			# races the boundary that flips cur_room, so it sometimes lets
			# a fast turn-around slip out. Shoving the player back into the
			# playable rect is frame-race-free. You only leave a live room
			# by dying (respawn at the last safe room).
			var pr := play_rect(cur_room)
			player.global_position.x = clampf(player.global_position.x, pr.position.x + 52.0, pr.end.x - 52.0)
			player.global_position.y = clampf(player.global_position.y, pr.position.y + 62.0, pr.end.y - 62.0)
		else:
			_enter_room(zi)
	hud.set_zone(zones[cur_room]["name"])
	# MP: the sim gate follows every player, every frame (remote players
	# move between the local room transitions above). Solo: {cur_room}.
	_refresh_active_rooms()
	_host_ensure_active_rooms()  # MP: populate any room a guest reached first

	# ------------------------------------------------ terrain mechanics ---
	var cur_terrain := Terrains.get_terrain(terrain_by_zone[cur_room])
	if cur_terrain.get("event", "") != "" and state == ST_PLAYING and not player.dead:
		terrain_event_t -= delta
		if terrain_event_t <= 0.0:
			var span: Array = cur_terrain.get("event_t", [5.0, 8.0])
			terrain_event_t = randf_range(span[0], span[1])
			run_terrain_event(cur_terrain["event"])
	if cur_terrain.get("mp_boost", false):  # crystal caverns hum with mana
		player.mp = minf(player.max_mp, player.mp + 5.0 * delta)
	hazard_tick -= delta
	if hazard_tick <= 0.0:
		hazard_tick = 0.4
		_apply_hazards()
	if gust_t > 0.0:
		gust_t -= delta
		if gust_t <= 0.0:
			gust_vec = Vector2.ZERO

	# Dev god mode: unkillable, infinite mana, no cooldowns.
	if dev_god:
		player.hp = player.max_hp
		player.mp = player.max_mp
		for key in player.cds:
			player.cds[key] = minf(player.cds[key], 0.2)

	_update_barrier()

	# Ambient particles drift around the camera; NPCs chatter idly.
	if is_instance_valid(ambient_fx):
		ambient_fx.global_position = player.global_position + Vector2(0, -380.0 if ambient_above else 0.0)
	npc_emote_t -= delta
	if npc_emote_t <= 0.0:
		npc_emote_t = randf_range(3.5, 7.0)
		if not interactables.is_empty() and state == ST_PLAYING and not hud.dialogue_active:
			var entry: Dictionary = interactables[randi() % interactables.size()]
			if is_instance_valid(entry["node"]) and player.global_position.distance_to(entry["node"].position) < 700.0:
				emote(entry["node"], idle_emote_symbol())

	# New theme unlocked: announce it.
	if player.pending_theme_note != "" and state == ST_PLAYING and not hud.dialogue_active and not menus.is_open():
		hud.flash_title("THEME UNLOCKED: " + player.pending_theme_note,
			"Press T to assign themes to your abilities", 2.2)
		sfx("victory")
		player.pending_theme_note = ""

	# NPC interactions (elder, merchants). Interact is GAMEPLAY input — it
	# fires convos/chests/desks in the shared world — so it routes through
	# the player's intents (MP seam). The poll-through refresh keeps the
	# old live-read timing (_process outruns physics frames headless).
	interact_in_range = false  # recomputed below; stays false while a menu/dialogue is up
	# A CHOICE prompt is its own overlay flag — dialogue_active drops before
	# dialogue_choice raises choices_active (hud.gd) — so it gates here too:
	# in a session nothing pauses (§5.4), and an ungated poll kept firing
	# E-interacts (re-entering the convo under its own pending decision) and
	# moving the hero beneath the panel.
	var overlay_up: bool = hud.dialogue_active or hud.choices_active or menus.is_open()
	if state == ST_PLAYING and not overlay_up:
		player._poll_local_intents()
		for entry in interactables:
			if not is_instance_valid(entry["node"]):
				continue
			var near: bool = player.global_position.distance_to(entry["node"].position) < 80.0
			entry["prompt"].visible = near
			if near:
				interact_in_range = true  # the touch Act button appears only when this is true
			if near and talk_cd <= 0.0 and player.intent_interact:
				talk_cd = 0.6
				_face_interactable_to_player(entry)
				entry["action"].call()
				break
		# MP-12 × touch: the Act button must ALSO appear beside a fallen ally —
		# holding it IS the revive channel (player.gd _revive_channel_tick reads
		# intent_interact), and a phone has no E key. Range mirrors the channel's
		# own REVIVE_REACH so the button shows exactly where holding it works.
		# Without this the button never surfaced (interactables holds NPCs and
		# desks, never players) and revive was unreachable on touch.
		if net_online() and not player.downed and not player.ghost:
			for q in players:
				if q != null and is_instance_valid(q) and q != player \
						and (q.downed or q.ghost) \
						and player.global_position.distance_to(q.global_position) <= player.REVIVE_REACH:
					interact_in_range = true
					break
		# Menu hotkeys. MP: UI-local, per-client — opening your inventory or
		# map is presentation, not simulation; these never become intents.
		if talk_cd <= 0.0:
			if Input.is_key_pressed(binds["inventory"]):
				talk_cd = 0.4
				menus.open_inventory()
			elif Input.is_key_pressed(binds["skills"]):
				talk_cd = 0.4
				menus.open_skills()
			elif Input.is_key_pressed(binds["codex"]):
				talk_cd = 0.4
				menus.open_codex()
			elif Input.is_key_pressed(binds.get("map", KEY_M)):
				talk_cd = 0.4
				menus.open_map()
			# (ESC → pause menu lives in hud._on_escape, event-driven —
			# a polled duplicate here caused double-open/close races.)
	elif state == ST_PLAYING and has_local_player():
		# Overlay up: polling is skipped, and intents HOLD their last polled
		# value — online (no pause) a key held when the overlay opened would
		# keep walking/casting the hero underneath it. Zero them every frame
		# an overlay is up; the touch HUD already zeroes its own side
		# (_release_everything on the overlay gate).
		player.clear_local_intents()

	shake_amt = move_toward(shake_amt, 0.0, 20.0 * delta)
	if camera:
		camera.offset = Vector2(randf_range(-1, 1), randf_range(-1, 1)) * shake_amt
	# (The room-transition check at the top of _process is the safety
	# net: any position outside the graph snaps back into the room.)
