class_name Game extends "res://scripts/game_flow.gd"
## GAME, layer 4 of 4 — boot (_ready, class select, save loading) and
## the per-frame driver. See game_base.gd for the chain layout.

# The transport autoload's SCRIPT, for enums/consts only — the bare
# `NetworkManager` global doesn't exist under check_compile (MP-05).
const NetManager := preload("res://scripts/net/net_manager.gd")

# --- MP session entry (dev-facing, MP-07; MP-08 builds the real lobby UI
# on these same seams). Layer-local state: only the boot flow reads them.
# The net test sets them directly before add_child; the CLI parse in
# _ready fills them from the user args.
var mp_host := false        # --mp-host[=ip:port]: host while playing normally
var mp_host_code := ""      # optional listen override (default 127.0.0.1:9999)
var mp_join_code := ""      # --mp-join=<code>: skip the title flow, join + handshake
var mp_cls := "warrior"     # --mp-cls=<class>: the joiner's dev character class


## Filenames in an override asset dir (assets/<dir>, e.g. "sounds"/"music").
## Editor/source scans the folder live, so dropping in a file just works.
## An exported build can't enumerate imported audio (it's remapped inside
## the .pck, not a loose file), so it reads assets/asset_manifest.json —
## baked into the pack by the export include_filter and regenerated by
## tools/gen_asset_manifest.py before each export.
func _override_files(dir: String) -> PackedStringArray:
	if OS.has_feature("template"):  # exported build
		var mpath := "res://assets/asset_manifest.json"
		if not FileAccess.file_exists(mpath):
			return PackedStringArray()
		var data: Variant = JSON.parse_string(FileAccess.get_file_as_string(mpath))
		var out := PackedStringArray()
		if data is Dictionary and data.has(dir):
			for f in data[dir]:
				out.append(String(f))
		return out
	var da := DirAccess.open("res://assets/" + dir)
	return da.get_files() if da else PackedStringArray()


func _ready() -> void:
	loot_rng.randomize()
	load_binds()
	Story.load_content()  # merge content modules before anything reads them
	dev_mode = "--dev" in OS.get_cmdline_user_args()
	# MP session flags (MP-07 dev entry — see _start_flow).
	for arg in OS.get_cmdline_user_args():
		var s := str(arg)
		if s == "--mp-host":
			mp_host = true
		elif s.begins_with("--mp-host="):
			mp_host = true
			mp_host_code = s.get_slice("=", 1)
		elif s.begins_with("--mp-join="):
			mp_join_code = s.get_slice("=", 1)
		elif s.begins_with("--mp-cls="):
			mp_cls = s.get_slice("=", 1)
	# Hand the session bridge its game: net_session.gd (a child of the
	# NetworkManager autoload) owns the join handshake + movement sync.
	var net_session: Node = get_node_or_null("/root/NetworkManager/Session")
	if net_session != null:
		net_session.game = self
	zones = Story.chapter(chapter_id)["zones"]
	zone_count = zones.size()
	for zone in zones:
		terrain_by_zone.append(zone.get("terrain", "village"))
	_prepare_rooms()

	sounds = Sfx.build_all()
	# Sound overrides: any assets/sounds/<name>.wav or .ogg replaces the
	# synthesized effect of the same name (same idea as sprites).
	for file in _override_files("sounds"):
		if not (file.ends_with(".wav") or file.ends_with(".ogg") or file.ends_with(".mp3")):
			continue
		# Loaded via the resource system so overrides survive an export:
		# a packed .pck has no loose files for load_from_file to reach.
		var res_path := "res://assets/sounds/" + file
		if not ResourceLoader.exists(res_path):
			continue
		var snd := load(res_path) as AudioStream
		if snd:
			sounds[file.get_basename()] = snd
	for i in 10:
		var sp := AudioStreamPlayer.new()
		sp.volume_db = -8.0
		add_child(sp)
		sound_pool.append(sp)

	# Background music: looping procedural chiptune, one per zone + boss.
	music_tracks = Music.build_all()
	# Music overrides: assets/music/<track>.ogg/.mp3/.wav replaces the
	# composed track of the same name, looped — same idea as sprites/sfx.
	for file in _override_files("music"):
		if not (file.ends_with(".ogg") or file.ends_with(".mp3") or file.ends_with(".wav")):
			continue
		# load() so music overrides apply in exported builds too.
		var res_path := "res://assets/music/" + file
		if not ResourceLoader.exists(res_path):
			continue
		var tune: Dictionary = MUSIC_TUNE.get(file.get_basename(), {})
		var track := load(res_path)
		if track is AudioStreamOggVorbis:
			var ogg := track as AudioStreamOggVorbis
			ogg.loop = true
			ogg.loop_offset = float(tune.get("start", 0.0))
			music_tracks[file.get_basename()] = ogg
		elif track is AudioStreamMP3:
			var mp3 := track as AudioStreamMP3
			mp3.loop = true
			mp3.loop_offset = float(tune.get("start", 0.0))
			music_tracks[file.get_basename()] = mp3
		elif track is AudioStreamWAV:
			var wav := track as AudioStreamWAV
			wav.loop_mode = AudioStreamWAV.LOOP_FORWARD
			wav.loop_end = wav.data.size() / (4 if wav.stereo else 2)
			music_tracks[file.get_basename()] = wav
	music_player = AudioStreamPlayer.new()
	music_player.volume_db = -16.0
	# Music survives the pause: boot menus (cover/roster) run with the
	# tree paused, and the pause menu shouldn't strangle the track.
	music_player.process_mode = Node.PROCESS_MODE_ALWAYS
	add_child(music_player)
	amb_player = AudioStreamPlayer.new()
	amb_player.volume_db = AMB_DB
	amb_player.process_mode = Node.PROCESS_MODE_ALWAYS
	add_child(amb_player)
	load_settings()
	apply_audio_settings()
	apply_display_settings()

	ambient = CanvasModulate.new()
	ambient.color = Terrains.get_terrain(terrain_by_zone[0])["tint"]
	add_child(ambient)

	# 2D glow (needs Forward+ and viewport/hdr_2d, set in project.godot):
	# additive FX stacks (spell impacts, ult flashes, loot beams) push past
	# 1.0 brightness and bloom; ordinary sprites sit under the threshold.
	glow_env = WorldEnvironment.new()
	var env := Environment.new()
	env.background_mode = Environment.BG_CANVAS
	env.glow_enabled = true
	env.glow_blend_mode = Environment.GLOW_BLEND_MODE_ADDITIVE
	env.glow_hdr_threshold = 1.1
	env.glow_intensity = 0.55
	env.glow_bloom = 0.0
	env.set_glow_level(1, 0.5)
	env.set_glow_level(3, 1.0)
	env.set_glow_level(5, 0.6)
	glow_env.environment = env
	add_child(glow_env)

	world = Node2D.new()
	world.y_sort_enabled = true  # world children sort with the player
	add_child(world)
	_build_door_seals()

	player = Player.new()
	player.game = self
	player.global_position = _start_pos()
	add_child(player)

	reticle = Sprite2D.new()
	reticle.texture = Art.tex("reticle")
	reticle.scale = Vector2(2, 2)
	reticle.z_index = 25
	reticle.visible = false
	add_child(reticle)
	# Target's level floats above the lock-on brackets.
	reticle_label = Label.new()
	reticle_label.position = Vector2(-30, -24)
	reticle_label.size = Vector2(60, 14)
	reticle_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	reticle_label.scale = Vector2(0.5, 0.5)
	reticle_label.add_theme_font_size_override("font_size", 20)
	reticle_label.add_theme_color_override("font_outline_color", Color(0, 0, 0))
	reticle_label.add_theme_constant_override("outline_size", 6)
	reticle.add_child(reticle_label)

	camera = Camera2D.new()
	camera.position_smoothing_enabled = true
	camera.position_smoothing_speed = 8.0
	camera.zoom = Vector2(1.12, 1.12)  # slightly closer = chunkier pixels
	player.add_child(camera)
	camera.make_current()

	hud = Hud.new()
	hud.game = self
	add_child(hud)
	refresh_quest()

	menus = Menus.new()
	menus.game = self
	add_child(menus)

	# Build and enter the starting room (the rest of the graph is lazy).
	_enter_room(room_at_pos(player.global_position))

	# First: pick a class. Then the story begins.
	call_deferred("_start_flow")

func _start_flow() -> void:
	if mp_join_code != "":
		_mp_join_boot()  # joiner: no title flow — the world comes from the host
		return
	if mp_host:
		_mp_host_boot()  # host: start listening, then play normally below
	if no_saves:
		menus.open_chapter_select()  # autotest: straight to the pick
	else:
		# Real players always land on the cover, saves or none:
		# cover -> character roster -> (new hero) chapter + class select.
		menus.open_title()


## --mp-host: listen on ENET_DIRECT (dev default 127.0.0.1:9999) while
## the normal title flow proceeds. Guests are ADMITTED immediately (the
## MP-05 version gate), but the world snapshot only goes out once a
## character is picked/loaded — net_session's handshake waits for
## play_started. Fire-and-forget coroutine.
func _mp_host_boot() -> void:
	var net: Node = get_node("/root/NetworkManager")
	var err: Error = await net.host(NetManager.Mode.ENET_DIRECT, mp_host_code)
	print("[mp] host session: %s — code %s" % [error_string(err), str(net.session_code)])


## --mp-join=<code>: the wave-4 dev joiner. Skips the title flow — a dev
## character (mp_cls, level 1) rides in; the host's snapshot (chapter,
## seed, flags) arrives via net_session.gd after admission and rebuilds
## the world locally (MULTIPLAYER.md §4.1 row 1). Real players go through
## the lobby instead (MP-08, ui/lobby.gd) — it puts their roster SLOT in
## local_char and the snapshot handler loads that save's character.
func _mp_join_boot() -> void:
	var sess: Node = get_node("/root/NetworkManager/Session")
	sess.local_char = {"cls": mp_cls, "level": 1}
	var net: Node = get_node("/root/NetworkManager")
	var err: Error = await net.join(mp_join_code)
	print("[mp] join %s: %s" % [mp_join_code, error_string(err)])

func on_class_chosen(id: String) -> void:
	player.set_class(id)
	wander_seed = randi() % 1000000  # seeds this character's layout + rolled rooms
	reset_run_stats()  # the results card starts counting from here
	switch_chapter(chapter_id, true)  # lay out THIS run's world from the fresh seed
	if not no_saves:
		save_slot = SaveGame.next_free_slot()
	request_pause(false)
	# The class-select menu hid the HUD on the way in — and the opening's
	# dialogue box and cutscene stage are its CHILDREN, so it must come back
	# BEFORE the convo below or the whole opening plays invisibly (a "frozen"
	# game to the player). The cutscene's full-screen stage covers the
	# gameplay bars, so nothing gameplay-shaped leaks into the cinematic.
	hud.visible = true
	var begin := func() -> void:
		play_started = true
		set_music(Terrains.get_terrain(terrain_by_zone[cur_room]).get("music", "village"))
		hud.flash_title(zones[cur_room]["name"], String(Story.chapter(chapter_id)["name"]))
		autosave()
	if Story.ALL_CONVOS.has("open_" + id):
		# Class openings replace the generic intro: a staged cinematic
		# plays under the words (cues in Story.CONVOS), and a choice
		# moves Resonance before Maren ever appears.
		set_flag("opened_" + id)
		cutscene = Cutscene.new(self)
		hud.add_child(cutscene)
		# Above the gameplay HUD (bars/quest/abilities), under the words.
		hud.move_child(cutscene, hud.dialogue_box.get_index())
		run_convo_id("open_" + id, func() -> void:
			if cutscene:
				var cs := cutscene
				cutscene = null
				cs.finish(begin)
			else:
				begin.call())
	else:
		hud.dialogue(Story.ALL_BEATS["intro"], begin)

## Resume a saved character: restore the player + story flags onto the
## freshly built world, then skip straight into play (no intro).
func load_save(slot: int) -> void:
	var data := SaveGame.read(slot)
	if data.is_empty():
		return
	save_slot = slot
	guest_world = false  # resuming OUR world: full autosaves again (MP-08)
	# The layout is a pure function of wander_seed: restore the seed
	# FIRST, then force-rebuild so the world matches the saved one.
	wander_seed = int(SaveGame.world_of(data).get("wander_seed", 0))
	switch_chapter(String(data.get("chapter", "ch1")), true)
	SaveGame.apply(self, data)
	request_pause(false)
	play_started = true
	hud.visible = true  # the load menu hid it on the way in
	set_music(Terrains.get_terrain(terrain_by_zone[cur_room]).get("music", "village"))
	hud.flash_title(zones[cur_room]["name"], "The tale continues")

## Rebuild the world state a save implies: mark dead bosses' rooms
## resolved and re-check every built gate against the restored flags
## and kills. (Unbuilt rooms evaluate their locks at build time.)
func reconcile_after_load() -> void:
	if talked_to_elder and not get_flag("met_elder", false):
		set_flag("met_elder")  # pre-graph saves stored only the bool
	for zi in zone_count:
		var kind: String = zones[zi].get("boss", "")
		if kind != "" and boss_done.get(kind, false):
			boss_spawned[zi] = true
			zone_alive[zi] = 0
			cleared[zi] = true
	_recheck_gates()
	refresh_quest()

func _process(delta: float) -> void:
	talk_cd = maxf(0.0, talk_cd - delta)
	if hud.dialogue_active or menus.is_open():
		talk_cd = 0.4
	if play_started and state == ST_PLAYING:
		run_time += delta  # chapter run clock (results card; pauses pause it)
	refresh_ambience()  # ambient bed tracks the room's terrain (cheap no-op)
	track_footprints()  # snow remembers your steps (no-op off snow)
	tick_footsteps(delta)  # and every step SOUNDS (plate classes clank)

	# HUD, reticle and boss bar are PER-CLIENT presentation (MULTIPLAYER.md
	# §5.6): they bind to local_player — the player on THIS screen. Solo:
	# local_player == player, pixel-identical.
	hud.update_stats(local_player)

	# Reticle over the enemy your AIMED attacks would hit — the facing-gated
	# target, or the hard-locked one (orange). Hides when nothing is on your
	# side, which is itself the cue to turn and face a foe.
	var target := local_player.aim_focus()
	if target and not local_player.dead:
		reticle.visible = true
		reticle.global_position = target.global_position
		reticle.modulate = Color(1.0, 0.45, 0.2) if target == local_player.locked_target else Color(1, 1, 1)
		reticle_label.text = "Lv %d" % target.level
		# Color the level by threat vs your own level.
		var diff := target.level - local_player.level
		reticle_label.add_theme_color_override("font_color",
			Color(1, 0.35, 0.3) if diff >= 3 else (Color(1, 0.85, 0.4) if diff >= 0 else Color(0.6, 1, 0.6)))
	else:
		reticle.visible = false

	# The boss bar follows your TARGET: the locked/aimed boss if any,
	# else the first live one (endgame brawls run up to 5 at once).
	var live_bosses := _live_bosses()
	if not live_bosses.is_empty():
		var shown: Boss = local_player.locked_target as Boss
		if shown == null or not is_instance_valid(shown) or shown.dying:
			shown = target as Boss  # the auto-aim pick from above
		if shown == null or not live_bosses.has(shown):
			shown = live_bosses[0] if current_boss == null or not live_bosses.has(current_boss) else current_boss
		if shown != current_boss:
			current_boss = shown
			hud.show_boss_bar(shown.display_name)
		hud.update_boss_bar(current_boss.hp / current_boss.max_hp)
		# Fight-report bookkeeping: our first blood engages the clock
		# (a boss's first hit engages via take_damage); brawl
		# reinforcements join the HP pool the frame they appear.
		if fight_active:
			for b in live_bosses:
				fight_track(b)
			fight_time += delta
		else:
			for b in live_bosses:
				if b.hp < b.max_hp - 0.5:
					fight_engage()
					break

	# Room transitions: walking through a doorway moves you next door.
	# (Aggro is per-pack now — entering a room wakes nobody by itself.)
	var zi := room_at_pos(player.global_position)
	if zi == -1:
		# Physics glitch outside the graph: snap back into the room.
		var rr := play_rect(clampi(cur_room, 0, zone_count - 1))
		player.global_position.x = clampf(player.global_position.x, rr.position.x + 52.0, rr.end.x - 52.0)
		player.global_position.y = clampf(player.global_position.y, rr.position.y + 62.0, rr.end.y - 62.0)
		zi = cur_room
	elif zi != cur_room and state == ST_PLAYING:
		if _room_hot(cur_room):
			# Locked in: a HOT room seals every exit until it's purged (or
			# the boss falls). The pulsing seal glow is feedback; THIS is
			# the wall — the seal body sits a step outside the cell and
			# races the boundary that flips cur_room, so it sometimes lets
			# a fast turn-around slip out. Shoving the player back into the
			# playable rect is frame-race-free. You only leave a live room
			# by dying (respawn at the last safe room).
			var pr := play_rect(cur_room)
			player.global_position.x = clampf(player.global_position.x, pr.position.x + 52.0, pr.end.x - 52.0)
			player.global_position.y = clampf(player.global_position.y, pr.position.y + 62.0, pr.end.y - 62.0)
		else:
			_enter_room(zi)
	hud.set_zone(zones[cur_room]["name"])
	# MP: the sim gate follows every player, every frame (remote players
	# move between the local room transitions above). Solo: {cur_room}.
	_refresh_active_rooms()

	# ------------------------------------------------ terrain mechanics ---
	var cur_terrain := Terrains.get_terrain(terrain_by_zone[cur_room])
	if cur_terrain.get("event", "") != "" and state == ST_PLAYING and not player.dead:
		terrain_event_t -= delta
		if terrain_event_t <= 0.0:
			var span: Array = cur_terrain.get("event_t", [5.0, 8.0])
			terrain_event_t = randf_range(span[0], span[1])
			run_terrain_event(cur_terrain["event"])
	if cur_terrain.get("mp_boost", false):  # crystal caverns hum with mana
		player.mp = minf(player.max_mp, player.mp + 5.0 * delta)
	hazard_tick -= delta
	if hazard_tick <= 0.0:
		hazard_tick = 0.4
		_apply_hazards()
	if gust_t > 0.0:
		gust_t -= delta
		if gust_t <= 0.0:
			gust_vec = Vector2.ZERO

	# Dev god mode: unkillable, infinite mana, no cooldowns.
	if dev_god:
		player.hp = player.max_hp
		player.mp = player.max_mp
		for key in player.cds:
			player.cds[key] = minf(player.cds[key], 0.2)

	_update_barrier()

	# Ambient particles drift around the camera; NPCs chatter idly.
	if is_instance_valid(ambient_fx):
		ambient_fx.global_position = player.global_position + Vector2(0, -380.0 if ambient_above else 0.0)
	npc_emote_t -= delta
	if npc_emote_t <= 0.0:
		npc_emote_t = randf_range(3.5, 7.0)
		if not interactables.is_empty() and state == ST_PLAYING and not hud.dialogue_active:
			var entry: Dictionary = interactables[randi() % interactables.size()]
			if is_instance_valid(entry["node"]) and player.global_position.distance_to(entry["node"].position) < 700.0:
				emote(entry["node"], idle_emote_symbol())

	# New theme unlocked: announce it.
	if player.pending_theme_note != "" and state == ST_PLAYING and not hud.dialogue_active and not menus.is_open():
		hud.flash_title("THEME UNLOCKED: " + player.pending_theme_note,
			"Press T to assign themes to your abilities", 2.2)
		sfx("victory")
		player.pending_theme_note = ""

	# NPC interactions (elder, merchants). Interact is GAMEPLAY input — it
	# fires convos/chests/desks in the shared world — so it routes through
	# the player's intents (MP seam). The poll-through refresh keeps the
	# old live-read timing (_process outruns physics frames headless).
	if state == ST_PLAYING and not hud.dialogue_active and not menus.is_open():
		player._poll_local_intents()
		for entry in interactables:
			var near: bool = player.global_position.distance_to(entry["node"].position) < 80.0
			entry["prompt"].visible = near
			if near and talk_cd <= 0.0 and player.intent_interact:
				talk_cd = 0.6
				entry["action"].call()
				break
		# Menu hotkeys. MP: UI-local, per-client — opening your inventory or
		# map is presentation, not simulation; these never become intents.
		if talk_cd <= 0.0:
			if Input.is_key_pressed(binds["inventory"]):
				talk_cd = 0.4
				menus.open_inventory()
			elif Input.is_key_pressed(binds["skills"]):
				talk_cd = 0.4
				menus.open_skills()
			elif Input.is_key_pressed(binds["codex"]):
				talk_cd = 0.4
				menus.open_codex()
			elif Input.is_key_pressed(binds.get("map", KEY_M)):
				talk_cd = 0.4
				menus.open_map()
			# (ESC → pause menu lives in hud._on_escape, event-driven —
			# a polled duplicate here caused double-open/close races.)

	shake_amt = move_toward(shake_amt, 0.0, 20.0 * delta)
	if camera:
		camera.offset = Vector2(randf_range(-1, 1), randf_range(-1, 1)) * shake_amt
	# (The room-transition check at the top of _process is the safety
	# net: any position outside the graph snaps back into the room.)
