## capital_hub — Crownfall, the capital (reworked 2026-07-25, see
## PROPOSALS/CAPITAL_REWORK.md). A STANDALONE 9-room authored city on a 3x3
## grid: Crown Plaza holds every everyday service (forge, lapidary, vault,
## bazaar + wardrobe, mail, alms), and every branch room — portals, archive,
## tavern, gate, and the four faction wards — is exactly one door away.
## Reached via the Travel button, the dev panel, and (first ch1 clear) the
## campaign routing; Story.chapter("capital") resolves this CHAPTER.
##
## Fixed layout: every zone carries an authored "coord" + "exits", so
## game_world._prepare_rooms lays them out verbatim (no seeded spine).
## All zones are "safe" (no packs). ONE ACCESS POINT PER FUNCTION: services
## with favor attribution live on NPCs (action + optional one-time "greet"
## convo); props own the impersonal functions (portals, vault, desks);
## landmarks with no "uses" are scenery for the NPC in front of them.
## GENERATED by tools/content/gen_capital.py — edit the generator, not this file.
class_name CapitalHub

# The standalone world. Story.chapter("capital") returns this; it is kept OUT of
# CHAPTER_LIST so campaign machinery (chapter select, weekly rotation, act gating)
# never sees it — exactly like the endgame arenas.
const CHAPTER := {
	"name": "Crownfall",
	"sub": "A gathering city — every service one plaza, every road one door",
	"standalone": true,
	"loot_cap": "C",
	"start_quest": "",
	"final_boss": "",
	"start_pos": [1056, 624],
	"zones": [
	{"name": "Crown Plaza", "terrain": "capital_civic", "type": "safe",
		"coord": [0, 0], "room_scale": 1.00, "exits": ["N", "S", "E", "W"], "enemies": [], "boss": "",
		"district": "heart", "mark": "★",
		"obstacles": [], "obstacle_count": 0,
		"decor": [], "decor_count": 0, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_crown_spire_gate", "x": 1056, "y": 500, "clearance": 430, "uses": [{"type": "action", "prompt": "E — View the city map", "x": 0, "y": 30, "ref": "map"}]}, {"name": "capital_crown_fountain", "x": 1056, "y": 765, "clearance": 250, "uses": [{"type": "inspect", "prompt": "E — Inspect the Crown Fountain", "x": 0, "y": 105, "title": "Crown Fountain", "text": "The ward roads meet at this basin. Companies use its crown as the city's easiest rally point."}]}, {"name": "capital_ashfire_forge", "x": 430, "y": 560, "clearance": 260, "uses": []}, {"name": "capital_grand_archive", "x": 1680, "y": 560, "clearance": 235, "uses": []}, {"name": "capital_market_stall", "x": 1620, "y": 860, "clearance": 200, "uses": [{"type": "action", "prompt": "E — Browse the Wardrobe", "x": 0, "y": 100, "ref": "wardrobe"}]}, {"name": "capital_market_stall", "x": 490, "y": 860, "clearance": 200, "uses": [{"type": "action", "prompt": "E — Check your mailbox", "x": 0, "y": 100, "ref": "mail"}]}],
		"furnishings": [{"name": "capital_city_bench", "x": 700, "y": 990, "clearance": 110}, {"name": "capital_city_bench", "x": 1410, "y": 990, "clearance": 110}],
		"backdrops": [{"name": "capital_city_arcade", "x": 1056, "y": 405, "w": 1680}],
		"merchant": [1470, 830],
		"npcs": [
			{"sprite": "factor_imre", "x": 1290, "y": 830, "prompt": "E — Ask for directions", "convo": "cap_citizen"},
			{"sprite": "smith_petra", "x": 470, "y": 700, "prompt": "E — Smith Petra", "action": "forge", "greet": "cap_petra"},
			{"sprite": "archivist_lene", "x": 1640, "y": 700, "prompt": "E — Master Lapidary", "action": "lapidary", "greet": "cap_lapidary"},
			{"sprite": "warden_corin", "x": 1240, "y": 580, "prompt": "E — Marshal Corin", "action": "drill"},
			{"sprite": "clerk_voss", "x": 830, "y": 830, "prompt": "E — Claim the daily alms", "action": "daily"},
			{"sprite": "capital_vault_chest", "x": 1056, "y": 950, "prompt": "E — Open your vault", "action": "vault"}],
	},
	{"name": "Wayfinder Sanctum", "terrain": "capital_wayfinder", "type": "safe",
		"coord": [0, -1], "room_scale": 0.82, "exits": ["S", "E", "W"], "enemies": [], "boss": "",
		"district": "civic", "mark": "◆",
		"obstacles": [], "obstacle_count": 0,
		"decor": [], "decor_count": 0, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_portal_story", "x": 560, "y": 560, "clearance": 150, "uses": [{"type": "action", "prompt": "E — Enter the Story Gate", "x": 0, "y": 30, "ref": "portal_story"}]}, {"name": "capital_portal_crucible", "x": 1056, "y": 560, "clearance": 160, "uses": [{"type": "action", "prompt": "E — Enter the Crucible Gate", "x": 0, "y": 30, "ref": "portal_crucible"}]}, {"name": "capital_portal_depths", "x": 1552, "y": 560, "clearance": 145, "uses": [{"type": "action", "prompt": "E — Enter the Depths Gate", "x": 0, "y": 30, "ref": "portal_depths"}]}],
		"furnishings": [],
		"backdrops": [],
		"npcs": [],
	},
	{"name": "The Grand Archive", "terrain": "capital_civic", "type": "safe",
		"coord": [1, 0], "room_scale": 0.72, "exits": ["N", "S", "W"], "enemies": [], "boss": "",
		"district": "civic", "mark": "",
		"obstacles": [], "obstacle_count": 0,
		"decor": [], "decor_count": 0, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_grand_archive", "x": 1056, "y": 585, "clearance": 285, "uses": [{"type": "action", "prompt": "E — Browse the Codex", "x": -170, "y": 100, "ref": "codex"}, {"type": "action", "prompt": "E — Read your journal", "x": 0, "y": 100, "ref": "journal"}, {"type": "action", "prompt": "E — Review your records", "x": 170, "y": 100, "ref": "records"}]}],
		"furnishings": [],
		"backdrops": [{"name": "capital_city_arcade", "x": 1056, "y": 405, "w": 1680}],
		"npcs": [],
	},
	{"name": "The Ashen Tankard", "terrain": "capital_civic", "type": "safe",
		"coord": [-1, 0], "room_scale": 0.78, "exits": ["N", "S", "E"], "enemies": [], "boss": "",
		"district": "civic", "mark": "",
		"obstacles": [], "obstacle_count": 0,
		"decor": [], "decor_count": 0, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_ashen_tankard", "x": 1056, "y": 590, "clearance": 285, "uses": [{"type": "action", "prompt": "E — Find a company at the Tankard", "x": 0, "y": 95, "ref": "guild"}]}, {"name": "great_hearth", "x": 620, "y": 560, "clearance": 175, "uses": [{"type": "inspect", "prompt": "E — Warm yourself", "x": 0, "y": 90, "title": "The Great Hearth", "text": "A public fire for cooking, waiting, and finding companions between expeditions."}]}, {"name": "capital_alembic_station", "x": 1492, "y": 560, "clearance": 205, "uses": [{"type": "action", "prompt": "E — Prepare your potion loadout", "x": 0, "y": 80, "ref": "potions"}]}],
		"furnishings": [{"name": "capital_city_bench", "x": 760, "y": 810, "clearance": 110}, {"name": "capital_city_bench", "x": 1352, "y": 810, "clearance": 110}],
		"backdrops": [{"name": "capital_city_arcade", "x": 1056, "y": 405, "w": 1680}],
		"npcs": [
			{"sprite": "peddler_nix", "x": 1056, "y": 814, "prompt": "E — Tavern Keeper Nix", "convo": "cap_tankard"},
			{"sprite": "old_fenna", "x": 650, "y": 650, "prompt": "E — Old Fenna", "convo": "cap_fenna"}],
	},
	{"name": "The Emberward Gate", "terrain": "capital_approach", "type": "safe",
		"coord": [0, 1], "room_scale": 0.72, "exits": ["N", "E", "W"], "enemies": [], "boss": "",
		"district": "approach", "mark": "",
		"obstacles": [], "obstacle_count": 0,
		"decor": [], "decor_count": 0, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_emberward_gate", "x": 1056, "y": 560, "clearance": 280, "uses": [{"type": "action", "prompt": "E — Leave Crownfall", "x": 0, "y": 80, "ref": "portal_story"}]}],
		"furnishings": [],
		"backdrops": [{"name": "capital_city_arcade", "x": 1056, "y": 405, "w": 1680}],
		"npcs": [
			{"sprite": "warden_sighne", "x": 1056, "y": 814, "prompt": "E — Gate Sergeant", "convo": "cap_gate"}],
	},
	{"name": "Fangmoot Circle", "terrain": "capital_wildfang", "type": "safe",
		"coord": [-1, -1], "room_scale": 0.78, "exits": ["S", "E"], "enemies": [], "boss": "",
		"district": "wild", "mark": "●",
		"obstacles": [], "obstacle_count": 0,
		"decor": [], "decor_count": 0, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_wildfang_fangmoot", "x": 1056, "y": 570, "clearance": 285, "uses": [{"type": "action", "prompt": "E — Review Wildfang contracts", "x": 0, "y": 95, "ref": "journal"}]}],
		"furnishings": [{"name": "capital_city_bench", "x": 760, "y": 815, "clearance": 110}],
		"backdrops": [],
		"npcs": [
			{"sprite": "callis", "x": 720, "y": 650, "prompt": "E — Warden Callis", "convo": "cap_callis"},
			{"sprite": "skald_ottar", "x": 1390, "y": 650, "prompt": "E — Skald Ottar", "convo": "cap_ottar"}],
	},
	{"name": "The Rot-Chapel", "terrain": "capital_choir", "type": "safe",
		"coord": [1, -1], "room_scale": 0.78, "exits": ["S", "W"], "enemies": [], "boss": "",
		"district": "choir", "mark": "●",
		"obstacles": [], "obstacle_count": 0,
		"decor": [], "decor_count": 0, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_rot_chapel", "x": 1056, "y": 590, "clearance": 290, "uses": [{"type": "action", "prompt": "E — Review Choir contracts", "x": 0, "y": 90, "ref": "journal"}]}],
		"furnishings": [{"name": "capital_city_bench", "x": 760, "y": 815, "clearance": 110}],
		"backdrops": [],
		"npcs": [
			{"sprite": "cantor_ilse", "x": 720, "y": 650, "prompt": "E — Cantor Ilse", "convo": "cap_ilse"},
			{"sprite": "deacon_vela", "x": 1390, "y": 650, "prompt": "E — Deacon Vela", "convo": "cap_vela"}],
	},
	{"name": "Accord Commons", "terrain": "capital_accord", "type": "safe",
		"coord": [-1, 1], "room_scale": 0.78, "exits": ["N", "E"], "enemies": [], "boss": "",
		"district": "accord", "mark": "●",
		"obstacles": [], "obstacle_count": 0,
		"decor": [], "decor_count": 0, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_accord_longhouse", "x": 1056, "y": 590, "clearance": 315, "uses": [{"type": "action", "prompt": "E — Review Accord contracts", "x": 0, "y": 95, "ref": "journal"}]}],
		"furnishings": [{"name": "capital_city_bench", "x": 760, "y": 815, "clearance": 110}, {"name": "capital_city_bench", "x": 1352, "y": 815, "clearance": 110}],
		"backdrops": [{"name": "capital_city_arcade", "x": 1056, "y": 405, "w": 1680}],
		"npcs": [
			{"sprite": "elder", "x": 720, "y": 650, "prompt": "E — Elder Maren", "convo": "cap_maren"},
			{"sprite": "herbalist_kesh", "x": 1390, "y": 650, "prompt": "E — Herbalist Kesh", "convo": "cap_kesh"}],
	},
	{"name": "The Sable Court", "terrain": "capital_cinderborn", "type": "safe",
		"coord": [1, 1], "room_scale": 0.78, "exits": ["N", "W"], "enemies": [], "boss": "",
		"district": "cinder", "mark": "●",
		"obstacles": [], "obstacle_count": 0,
		"decor": [], "decor_count": 0, "accents": [], "structures": [],
		"landmarks": [{"name": "capital_sable_hall", "x": 1056, "y": 590, "clearance": 315, "uses": [{"type": "action", "prompt": "E — Review Cinderborn contracts", "x": 0, "y": 95, "ref": "journal"}]}],
		"furnishings": [],
		"backdrops": [{"name": "capital_city_arcade", "x": 1056, "y": 405, "w": 1680}],
		"npcs": [
			{"sprite": "aldric", "x": 720, "y": 650, "prompt": "E — Ser Aldric", "convo": "cap_aldric"},
			{"sprite": "vessa", "x": 1390, "y": 650, "prompt": "E — Envoy Vessa", "convo": "cap_vessa"}],
	},
	],
}

# One short line per named resident (the ch2-hub CONVOS pattern). Merged into
# Story.ALL_CONVOS via the CONTENT_MODULES registration.
const CONVOS := {
	"cap_citizen": {"start": "a", "nodes": {"a": {"who": "A Citizen", "text": "First visit? Everything a returning company needs rings this plaza — Petra's forge west, the Lapidary east, your vault by the fountain, the bazaar and mail at the south stalls. Gates north, Tankard west, Archive east, the four ward halls at the corners.", "next": ""}}},
	"cap_petra": {"start": "a", "nodes": {"a": {"who": "Smith Petra", "text": "The city's one forge worth the name. Quench, reforge, transmute — bring me the piece and the coin and I'll bring the fire. Spend enough seasons at my bench and you'll find my rates soften for a regular.", "next": ""}}},
	"cap_lapidary": {"start": "a", "nodes": {"a": {"who": "Master Lapidary", "text": "Petra handles metal; I handle what lives inside it. Stones, sockets, synthesis — all of it at these benches and nowhere else. Gems are patient work; patrons who keep coming back get my patient prices.", "next": ""}}},
	"cap_fenna": {"start": "a", "nodes": {"a": {"who": "Old Fenna", "text": "Kitchen on this side, Alembic on that — supper or medicine without crossing the square. Sit by the hearth if you're waiting on friends; someone always knows who just came through a gate.", "next": ""}}},
	"cap_tankard": {"start": "a", "nodes": {"a": {"who": "Tavern Keeper", "text": "The Ashen Tankard — warmth, rumour, a fire that behaves. The whole city drifts through after dark. First cup's on the house for a shard-bearer.", "next": ""}}},
	"cap_gate": {"start": "a", "nodes": {"a": {"who": "Gate Sergeant", "text": "The Emberward Gate. Portcullis stays up in peacetime; the wild stays out on its honour. You came in clean — most do.", "next": ""}}},
	"cap_callis": {"start": "a", "nodes": {"a": {"who": "Warden Callis", "text": "The tribes hold this enclave by truce, not welcome. Honest work, then: survey what the Waking's made of the east, and bring us word. Daily, if you're able.", "next": ""}}},
	"cap_ottar": {"start": "a", "nodes": {"a": {"who": "Skald Ottar", "text": "A fire that never dies and a skald who never stops. Go do a thing worth singing — I'll trade you the doing for the song. Come back with a story.", "next": ""}}},
	"cap_ilse": {"start": "a", "nodes": {"a": {"who": "Cantor Ilse", "text": "The Choir does not bury its dead — rot is the land's honest truth, and the dead keep their own vigil here. Tend them with me. It's patient work. Daily work.", "next": ""}}},
	"cap_vela": {"start": "a", "nodes": {"a": {"who": "Deacon Vela", "text": "Quieter tasks than the Cantor's: recover a relic, carry a name north to the sleepers, witness a thing and return unbroken. The blight rewards the faithful.", "next": ""}}},
	"cap_maren": {"start": "a", "nodes": {"a": {"who": "Elder Maren", "text": "So — the shards still choosing, and the factions still counting. The Accord holds this ward and half this city's conscience. There's honest work daily, if you want it. Sit; the fire doesn't bite.", "next": ""}}},
	"cap_kesh": {"start": "a", "nodes": {"a": {"who": "Herbalist Kesh", "text": "Cures for the ward, reagents for the Alembic across the plaza. I set the day's gathering. Bring back the right leaves and no one dies of the wrong ones.", "next": ""}}},
	"cap_aldric": {"start": "a", "nodes": {"a": {"who": "Ser Aldric", "text": "The Cinderborn keep the forms of a court that lost its crown. I keep its sword arm. There's work in the old key — recover, restore, avenge — for a crown that might yet find a head. Daily, if you've the stomach.", "next": ""}}},
	"cap_vessa": {"start": "a", "nodes": {"a": {"who": "Envoy Vessa", "text": "Work with us and be paid, protected, and remembered. I've a commission most days — a courier run, a quiet errand, imperial paper with teeth. First one's waiting.", "next": ""}}},
}


## Merge + integrity selftest: the world resolves, every zone is safe, scaled,
## composed around a landmark, and has an interaction; NPC refs are wired.
## Landmarks MAY be pure scenery (empty uses) when an NPC owns the function.
static func selftest(_game: Node2D) -> String:
	var ch: Dictionary = Story.chapter("capital")
	if ch.get("zones", []).size() != 9:
		return "capital: expected 9 zones, got %d" % ch.get("zones", []).size()
	var coords := {}
	var known_actions := ["codex", "daily", "drill", "forge", "guild", "journal", "lapidary", "mail", "map", "portal_crucible", "portal_depths", "portal_story", "potions", "records", "vault", "wardrobe"]
	for z in ch["zones"]:
		if z.get("type", "") != "safe":
			return "capital: zone %s is not safe" % z.get("name", "?")
		if not Terrains.DATA.has(String(z.get("terrain", ""))):
			return "capital: zone %s has unknown terrain %s" % [z.get("name","?"), z.get("terrain","")]
		var room_scale: float = float(z.get("room_scale", 1.0))
		if room_scale < 0.55 or room_scale > 1.0:
			return "capital: zone %s has invalid room_scale %.2f" % [z.get("name","?"), room_scale]
		if z.get("landmarks", []).is_empty():
			return "capital: zone %s has no authored landmark" % z.get("name", "?")
		var has_interaction: bool = z.has("merchant") or not z.get("npcs", []).is_empty()
		for landmark in z.get("landmarks", []):
			for use in landmark.get("uses", []):
				has_interaction = true
				var use_type := String(use.get("type", ""))
				if use_type not in ["action", "inspect"]:
					return "capital: landmark %s has invalid interaction type" % landmark.get("name", "?")
				if use_type == "action" and String(use.get("ref", "")) not in known_actions:
					return "capital: landmark action %s is not handled" % use.get("ref", "")
		if not has_interaction:
			return "capital: zone %s has no interaction" % z.get("name", "?")
		var c: Array = z.get("coord", [])
		var key := "%d,%d" % [int(c[0]), int(c[1])]
		if coords.has(key):
			return "capital: duplicate coord %s" % key
		coords[key] = true
		for npc in z.get("npcs", []):
			if npc.has("convo") and not Story.ALL_CONVOS.has(String(npc["convo"])):
				return "capital: NPC convo %s not registered" % npc["convo"]
			if npc.has("greet") and not Story.ALL_CONVOS.has(String(npc["greet"])):
				return "capital: NPC greet convo %s not registered" % npc["greet"]
			if npc.has("action") and String(npc["action"]) not in known_actions:
				return "capital: NPC action %s is not handled" % npc["action"]
			if Art.tex(String(npc["sprite"])) == null:
				return "capital: NPC sprite %s missing" % npc["sprite"]
	return ""
