## rv_na_gallery — the two packs the Pixel Crawler sweeps missed (2026-07-18):
## Raven Fantasy Icons (rv_* — a full 32px item-icon library: potions, food,
## crafting matter, quest curios, gear) and Ninja Adventure's animals (the
## livestock/wildlife gap — villages had no living thing that wasn't trying
## to kill you). Everything here is PLACEHOLDER (dev-launcher Future tab
## only) until a quest / profession / zone promotes it: drop the flag and
## give it a real home. Format: scripts/content/README.md.
class_name RvNaGallery

# {id: {name, desc, icon, grade?, placeholder?}} — merged into
# Story.ALL_QUEST_ITEMS; grantable via Items.make_quest_item(id).
const QUEST_ITEMS := {
	"rv_key_iron": {"name": "Iron Key", "icon": "rv_key_iron", "grade": "D", "placeholder": true,
		"desc": "Plain, heavy, honest. Whatever it opens was not meant to be interesting."},
	"rv_key_gold": {"name": "Gilded Key", "icon": "rv_key_gold", "grade": "C", "placeholder": true,
		"desc": "Gold plate over cheap iron. The lock it fits is the opposite."},
	"rv_key_emerald": {"name": "Emerald Key", "icon": "rv_key_emerald", "grade": "B", "placeholder": true,
		"desc": "Cut from a single stone. Turning it feels like asking permission."},
	"rv_key_violet": {"name": "Violet Key", "icon": "rv_key_violet", "grade": "B", "placeholder": true,
		"desc": "It is slightly warm, always. Nobody has admitted to owning the door."},
	"rv_tome_red": {"name": "Crimson Tome", "icon": "rv_tome_red", "grade": "C", "placeholder": true,
		"desc": "Bound in red leather that was not always leather. The index is in a second hand."},
	"rv_tome_blue": {"name": "Azure Tome", "icon": "rv_tome_blue", "grade": "C", "placeholder": true,
		"desc": "Tide-tables for a sea nobody has found. The margins are certain it exists."},
	"rv_scroll": {"name": "Worn Parchment", "icon": "rv_scroll", "grade": "D", "placeholder": true,
		"desc": "Folded and refolded until the creases became the message."},
	"rv_case_crimson": {"name": "Crimson Scroll Case", "icon": "rv_case_crimson", "grade": "C", "placeholder": true,
		"desc": "Courier's lacquer, army red. Sealed with wax older than the courier."},
	"rv_case_teal": {"name": "Teal Scroll Case", "icon": "rv_case_teal", "grade": "C", "placeholder": true,
		"desc": "Sea-colored and salt-stained. The letter inside is bone dry."},
	"rv_rune_pebble": {"name": "Rune Pebble", "icon": "rv_rune_pebble", "grade": "D", "placeholder": true,
		"desc": "River-smooth, with one mark cut deep. A word too old to be small talk."},
	"rv_runestone": {"name": "Runestone", "icon": "rv_runestone", "grade": "C", "placeholder": true,
		"desc": "Fits the palm like it was measured for one. The carving faces inward when you hold it right."},
	"rv_candle": {"name": "Tallow Candle", "icon": "rv_candle", "grade": "D", "placeholder": true,
		"desc": "Burned down and relit too many times. Someone kept a long vigil with this."},
	"rv_lantern": {"name": "Watch Lantern", "icon": "rv_lantern", "grade": "D", "placeholder": true,
		"desc": "Blue glass, dented shut. It has outlived three watchmen and holds no grudge."},
	"rv_lamp": {"name": "Ancient Lamp", "icon": "rv_lamp", "grade": "B", "placeholder": true,
		"desc": "Polished bright by hopeful thumbs. Whatever lived inside has already been let out."},
	"rv_charm": {"name": "Frog Charm", "icon": "rv_charm", "grade": "D", "placeholder": true,
		"desc": "A squat green fellow, carved smiling. Luck for travelers who cross water."},
	"rv_horseshoe": {"name": "Lucky Horseshoe", "icon": "rv_horseshoe", "grade": "D", "placeholder": true,
		"desc": "Hung points-up over three different doors. All three houses still stand."},
	"rv_chest": {"name": "Banded Chest", "icon": "rv_chest", "grade": "C", "placeholder": true,
		"desc": "Iron straps, stubborn hinges, no key. It rattles exactly once if you shake it."},
	"rv_urn": {"name": "Clay Urn", "icon": "rv_urn", "grade": "D", "placeholder": true,
		"desc": "Fired plain, sealed with pitch. Some jars are questions better left corked."},
	"rv_map": {"name": "Map Fragment", "icon": "rv_map", "grade": "C", "placeholder": true,
		"desc": "One corner of somewhere. The torn edge matches nothing sold in any shop."},
	"rv_pack": {"name": "Traveler's Pack", "icon": "rv_pack", "grade": "D", "placeholder": true,
		"desc": "Found upright on the road, straps buckled, owner absent. Packed for a longer trip than anyone takes."},
	"rv_star": {"name": "Star Talisman", "icon": "rv_star", "grade": "B", "placeholder": true,
		"desc": "Five points of hammered gold. Sailors swear by it; the sky declines to comment."},
	"rv_banner": {"name": "War Banner", "icon": "rv_banner", "grade": "C", "placeholder": true,
		"desc": "Red field, no device. An army that did not want to be remembered — or did not get the chance."},
	"rv_grimoire": {"name": "Sealed Grimoire", "icon": "rv_grimoire", "grade": "B", "placeholder": true,
		"desc": "Strapped shut in silver. The clasps are on the outside, which is the polite interpretation."},
	"rv_goblet_bronze": {"name": "Bronze Goblet", "icon": "rv_goblet_bronze", "grade": "D", "placeholder": true,
		"desc": "Dented at the rim where it was set down hard, once, after a toast that mattered."},
	"rv_goblet_crystal": {"name": "Crystal Goblet", "icon": "rv_goblet_crystal", "grade": "B", "placeholder": true,
		"desc": "Rings at a touch and holds the note. Wine poured into it goes quiet."},
	"rv_conch": {"name": "Deep Conch", "icon": "rv_conch", "grade": "C", "placeholder": true,
		"desc": "Gold-lipped and cold. Held to the ear it plays the sea — a sea, at least. Not necessarily ours."},
	"rv_medal": {"name": "Gold Medal", "icon": "rv_medal", "grade": "C", "placeholder": true,
		"desc": "Awarded for something, to someone, by somebody grateful. All three names have worn away."},
}

# Raven icon families + Ninja Adventure critters, grouped for the Future
# subtabs: alchemy / armory / supplies / provisions / critters.
const RELICS := {
	# ---- ALCHEMY (draughts & essences — the brewing-profession seed).
	# Promotion path: an Items.make_* consumable + shop/drop/brewing wiring.
	"rv_pot_slim": {"group": "alchemy", "name": "Slim Red Vial", "sprite": "rv_pot_slim", "placeholder": true,
		"lore": "One swallow, no more. Field medics call it a heartbeat in glass."},
	"rv_pot_round": {"group": "alchemy", "name": "Round Draught", "sprite": "rv_pot_round", "placeholder": true,
		"lore": "The standard measure. Every belt in every barracks has a loop this size."},
	"rv_pot_corked": {"group": "alchemy", "name": "Corked Flask", "sprite": "rv_pot_corked", "placeholder": true,
		"lore": "Corked hard enough to need teeth. Brewers say the pop is half the cure."},
	"rv_pot_bulb": {"group": "alchemy", "name": "Bulb Flask", "sprite": "rv_pot_bulb", "placeholder": true,
		"lore": "Round-bottomed — it cannot be set down half-finished. Alchemists think of everything."},
	"rv_pot_jar": {"group": "alchemy", "name": "Stoppered Jar", "sprite": "rv_pot_jar", "placeholder": true,
		"lore": "A double dose in honest glass. Shared by partners who trust each other's math."},
	"rv_pot_flagon": {"group": "alchemy", "name": "Red Flagon", "sprite": "rv_pot_flagon", "placeholder": true,
		"lore": "Tavern-sized. Nobody brews this much of anything gentle."},
	"rv_pot_carafe": {"group": "alchemy", "name": "Wide Carafe", "sprite": "rv_pot_carafe", "placeholder": true,
		"lore": "Meant for a table, poured into cups. Healing as a family meal."},
	"rv_pot_greater": {"group": "alchemy", "name": "Greater Draught", "sprite": "rv_pot_greater", "placeholder": true,
		"lore": "White-capped and serious. The label just says ALL OF IT."},
	"rv_pot_mini": {"group": "alchemy", "name": "Pocket Vial", "sprite": "rv_pot_mini", "placeholder": true,
		"lore": "Sewn into cuffs and boot-tops. The dose you forgot you were carrying."},
	"rv_pot_phial": {"group": "alchemy", "name": "Crimson Phial", "sprite": "rv_pot_phial", "placeholder": true,
		"lore": "Apothecary-labeled in a careful hand. The refund policy is notably absent."},
	"rv_ess_green": {"group": "alchemy", "name": "Verdant Essence", "sprite": "rv_ess_green", "placeholder": true,
		"lore": "Smells of cut grass and deep wells. Gardens lean toward an open bottle."},
	"rv_ess_violet": {"group": "alchemy", "name": "Violet Essence", "sprite": "rv_ess_violet", "placeholder": true,
		"lore": "Distilled dusk. A drop behind each ear and the dead find you easier to talk to."},
	"rv_ess_blue": {"group": "alchemy", "name": "Azure Essence", "sprite": "rv_ess_blue", "placeholder": true,
		"lore": "Cold off the glass from a pace away. Winter, bottled out of season."},
	# ---- ARMORY (Raven gear library — weapon tiers, shields, wardrobe).
	# Future itemization art: these are icon-grade, ready for real gear rows.
	"rv_arm_sword": {"group": "armory", "name": "Iron Sword", "sprite": "rv_arm_sword", "placeholder": true,
		"lore": "The militia standard. Ten thousand of these have won every war nobody sings about."},
	"rv_arm_greatsword": {"group": "armory", "name": "Iron Greatsword", "sprite": "rv_arm_greatsword", "placeholder": true,
		"lore": "Carried on the back, swung from the hips, apologized for never."},
	"rv_arm_scimitar": {"group": "armory", "name": "Iron Scimitar", "sprite": "rv_arm_scimitar", "placeholder": true,
		"lore": "A curve with an opinion. Cavalry steel that never forgave the infantry."},
	"rv_arm_axe": {"group": "armory", "name": "Iron Battleaxe", "sprite": "rv_arm_axe", "placeholder": true,
		"lore": "Doubles as a tool, which is how it gets through town gates."},
	"rv_arm_hammer": {"group": "armory", "name": "Iron Warhammer", "sprite": "rv_arm_hammer", "placeholder": true,
		"lore": "Armor's honest answer. Where it lands, smiths get work."},
	"rv_arm_morningstar": {"group": "armory", "name": "Morning Star", "sprite": "rv_arm_morningstar", "placeholder": true,
		"lore": "Named by someone with a dark sense of sunrise."},
	"rv_arm_bow": {"group": "armory", "name": "Hunting Bow", "sprite": "rv_arm_bow", "placeholder": true,
		"lore": "Deer first, then wolves, then whatever kept coming out of the treeline."},
	"rv_arm_crossbow": {"group": "armory", "name": "Crossbow", "sprite": "rv_arm_crossbow", "placeholder": true,
		"lore": "A week of training against a lifetime of archery, and the week usually wins."},
	"rv_arm_staff": {"group": "armory", "name": "Ashwood Staff", "sprite": "rv_arm_staff", "placeholder": true,
		"lore": "A red stone socketed in old ash. It hums when storms are three days out."},
	"rv_arm_shuriken": {"group": "armory", "name": "Throwing Star", "sprite": "rv_arm_shuriken", "placeholder": true,
		"lore": "Four points, folded steel, no sound. The argument you win from a rooftop."},
	"rv_arm_gauntlet": {"group": "armory", "name": "Clawed Gauntlet", "sprite": "rv_arm_gauntlet", "placeholder": true,
		"lore": "Three tines of polished steel over the knuckles. Handshakes became formal after these."},
	"rv_arm_gold_blade": {"group": "armory", "name": "Gilded Blade", "sprite": "rv_arm_gold_blade", "placeholder": true,
		"lore": "Parade steel that turned out to hold an edge. The honor guard was as surprised as the assassin."},
	"rv_arm_gold_axe": {"group": "armory", "name": "Gilded Axe", "sprite": "rv_arm_gold_axe", "placeholder": true,
		"lore": "Ceremonial, allegedly. The notches in the gold suggest otherwise."},
	"rv_arm_gold_bow": {"group": "armory", "name": "Gilded Bow", "sprite": "rv_arm_gold_bow", "placeholder": true,
		"lore": "Strung with flame-red cord. Draws warm, looses warmer."},
	"rv_arm_frost_blade": {"group": "armory", "name": "Frost Blade", "sprite": "rv_arm_frost_blade", "placeholder": true,
		"lore": "Blue steel that fogs in summer. Wounds from it close slow and cold."},
	"rv_arm_frost_bow": {"group": "armory", "name": "Frost Bow", "sprite": "rv_arm_frost_bow", "placeholder": true,
		"lore": "The string never quite thaws. Arrows leave it trailing white."},
	"rv_arm_frost_pike": {"group": "armory", "name": "Frost Pike", "sprite": "rv_arm_frost_pike", "placeholder": true,
		"lore": "A winter point on an autumn haft. Holds a line the way ice holds a lake."},
	"rv_arm_ember_blade": {"group": "armory", "name": "Ember Blade", "sprite": "rv_arm_ember_blade", "placeholder": true,
		"lore": "Forge-orange down the fuller, and not because of the light."},
	"rv_arm_night_blade": {"group": "armory", "name": "Night Blade", "sprite": "rv_arm_night_blade", "placeholder": true,
		"lore": "Violet steel that drinks lamplight. Duelists hate it; morticians recognize it."},
	"rv_arm_scythe": {"group": "armory", "name": "Reaper's Scythe", "sprite": "rv_arm_scythe", "placeholder": true,
		"lore": "Farm tool, grave habit. The harvest metaphor writes itself and keeps writing."},
	"rv_arm_wild_bow": {"group": "armory", "name": "Wildwood Bow", "sprite": "rv_arm_wild_bow", "placeholder": true,
		"lore": "Cut living and never quite died. It pulls toward the forest when you aim elsewhere."},
	"rv_arm_crystal_saber": {"group": "armory", "name": "Crystal Saber", "sprite": "rv_arm_crystal_saber", "placeholder": true,
		"lore": "Grown, not forged. It chimes on the draw — stealth was never the point."},
	"rv_arm_fey_arrow": {"group": "armory", "name": "Fey Arrow", "sprite": "rv_arm_fey_arrow", "placeholder": true,
		"lore": "Green-fletched and self-righting. Loosed into the dark, it finds something. Choose the dark carefully."},
	"rv_arm_buckler": {"group": "armory", "name": "Wooden Buckler", "sprite": "rv_arm_buckler", "placeholder": true,
		"lore": "Studded oak, tavern-tested. Cheap enough to lose, good enough to matter."},
	"rv_arm_shield_round": {"group": "armory", "name": "Steel Roundshield", "sprite": "rv_arm_shield_round", "placeholder": true,
		"lore": "Quartered and riveted. The dents cluster low-left, where cowards aim."},
	"rv_arm_shield_gilded": {"group": "armory", "name": "Gilded Shield", "sprite": "rv_arm_shield_gilded", "placeholder": true,
		"lore": "Gold scale over steel heart. It blinds as much as it blocks, on sunny days."},
	"rv_arm_plate": {"group": "armory", "name": "Steel Plate", "sprite": "rv_arm_plate", "placeholder": true,
		"lore": "A torso's worth of no. Heavy, loud, and worth every pound the first time."},
	"rv_arm_plate_gold": {"group": "armory", "name": "Gilded Plate", "sprite": "rv_arm_plate_gold", "placeholder": true,
		"lore": "Commander's fit. The gold says follow me; the dents say it worked."},
	"rv_arm_helm": {"group": "armory", "name": "Steel Helm", "sprite": "rv_arm_helm", "placeholder": true,
		"lore": "Visored and ventilated. The world through the slit is narrow and survivable."},
	"rv_arm_helm_gold": {"group": "armory", "name": "Gilded Helm", "sprite": "rv_arm_helm_gold", "placeholder": true,
		"lore": "Crested for the field, polished for the portrait."},
	"rv_arm_greaves": {"group": "armory", "name": "Gilded Greaves", "sprite": "rv_arm_greaves", "placeholder": true,
		"lore": "Bright to the knee. Marching order says mud; ceremony says otherwise; these say both."},
	"rv_arm_chainmail": {"group": "armory", "name": "Chain Hauberk", "sprite": "rv_arm_chainmail", "placeholder": true,
		"lore": "Ten thousand rings, each one somebody's afternoon. Rustles like rain and shrugs off worse."},
	"rv_arm_robe": {"group": "armory", "name": "Scholar's Robe", "sprite": "rv_arm_robe", "placeholder": true,
		"lore": "Teal wool, ink-stained cuffs. Armor class of a strong opinion."},
	"rv_arm_hat_witch": {"group": "armory", "name": "Pointed Hat", "sprite": "rv_arm_hat_witch", "placeholder": true,
		"lore": "The brim keeps off rain; the point keeps off questions."},
	"rv_arm_ring_gold": {"group": "armory", "name": "Gold Ring", "sprite": "rv_arm_ring_gold", "placeholder": true,
		"lore": "Unadorned and unengraved. The plainest rings carry the longest stories."},
	"rv_arm_ring_teal": {"group": "armory", "name": "Seaglass Ring", "sprite": "rv_arm_ring_teal", "placeholder": true,
		"lore": "Tumbled smooth by a patient ocean. Wearers dream of tides."},
	"rv_arm_amulet": {"group": "armory", "name": "Jade Amulet", "sprite": "rv_arm_amulet", "placeholder": true,
		"lore": "A green stone on a copper chain, warm against the sternum. It has opinions about danger."},
	"rv_arm_boots": {"group": "armory", "name": "Riding Boots", "sprite": "rv_arm_boots", "placeholder": true,
		"lore": "Broken in by somebody with somewhere to be. They remember the stirrup."},
	# ---- SUPPLIES (crafting matter — ores, ingots, gems, harvest, tools).
	"rv_mat_ingot_copper": {"group": "supplies", "name": "Copper Ingot", "sprite": "rv_mat_ingot_copper", "placeholder": true,
		"lore": "First metal every smith ruins, then loves. Warm-colored and forgiving."},
	"rv_mat_ingots_copper": {"group": "supplies", "name": "Copper Ingots", "sprite": "rv_mat_ingots_copper", "placeholder": true,
		"lore": "Stacked in threes, the way founders count. A kettle, a kettle, a church bell."},
	"rv_mat_ingot_silver": {"group": "supplies", "name": "Silver Ingot", "sprite": "rv_mat_ingot_silver", "placeholder": true,
		"lore": "Cold to the touch and fussy in the forge. Certain things fear it, which keeps the price up."},
	"rv_mat_ingots_silver": {"group": "supplies", "name": "Silver Ingots", "sprite": "rv_mat_ingots_silver", "placeholder": true,
		"lore": "A stack this size buys a farm, or arms a vampire hunter. Same estate sale, usually."},
	"rv_mat_ingot_gold": {"group": "supplies", "name": "Gold Ingot", "sprite": "rv_mat_ingot_gold", "placeholder": true,
		"lore": "Soft, useless for tools, and worth more than every tool in the shop."},
	"rv_mat_ingots_gold": {"group": "supplies", "name": "Gold Ingots", "sprite": "rv_mat_ingots_gold", "placeholder": true,
		"lore": "The stack that ends arguments and starts wars, in that order."},
	"rv_mat_gem_blue": {"group": "supplies", "name": "Cut Sapphire", "sprite": "rv_mat_gem_blue", "placeholder": true,
		"lore": "Faceted deep-water blue. Jewelers hold it to the light; enchanters hold it to the dark."},
	"rv_mat_gem_green": {"group": "supplies", "name": "Cut Emerald", "sprite": "rv_mat_gem_green", "placeholder": true,
		"lore": "Green enough to make a garden jealous. Flawed stones are cheaper and luckier."},
	"rv_mat_gem_red": {"group": "supplies", "name": "Cut Ruby", "sprite": "rv_mat_gem_red", "placeholder": true,
		"lore": "The color of the thing it always ends up buying."},
	"rv_mat_gem_amber": {"group": "supplies", "name": "Amber Drop", "sprite": "rv_mat_gem_amber", "placeholder": true,
		"lore": "Old sap, older light. Something very small is very patient inside it."},
	"rv_mat_gem_violet": {"group": "supplies", "name": "Cut Amethyst", "sprite": "rv_mat_gem_violet", "placeholder": true,
		"lore": "Sober-stone, the tavern keepers call it, and set it in their best goblets. It does not work."},
	"rv_mat_gem_moon": {"group": "supplies", "name": "Moonstone", "sprite": "rv_mat_gem_moon", "placeholder": true,
		"lore": "Cloudy by day, clear by night. It keeps the moon's hours, not yours."},
	"rv_mat_ore_copper": {"group": "supplies", "name": "Copper Ore", "sprite": "rv_mat_ore_copper", "placeholder": true,
		"lore": "Green-flecked rock, honest weight. The hills give it up without much of a fight."},
	"rv_mat_ore_iron": {"group": "supplies", "name": "Iron Ore", "sprite": "rv_mat_ore_iron", "placeholder": true,
		"lore": "Gray, grim, and the whole reason the town exists."},
	"rv_mat_crystal_raw": {"group": "supplies", "name": "Raw Crystal", "sprite": "rv_mat_crystal_raw", "placeholder": true,
		"lore": "An amber spar, uncut. It catches light that is not currently in the room."},
	"rv_mat_skull": {"group": "supplies", "name": "Beast Skull", "sprite": "rv_mat_skull", "placeholder": true,
		"lore": "Heavy-browed and horn-scarred. Trophy to some, reagent to others, warning to the smart."},
	"rv_mat_bone": {"group": "supplies", "name": "Beast Bone", "sprite": "rv_mat_bone", "placeholder": true,
		"lore": "Thick as a wrist and clean as a whistle. Carvers and necromancers bid against each other."},
	"rv_mat_pelt": {"group": "supplies", "name": "Tanned Pelt", "sprite": "rv_mat_pelt", "placeholder": true,
		"lore": "Scraped and stretched to a soft finish. Winter's argument, answered."},
	"rv_mat_egg": {"group": "supplies", "name": "Speckled Egg", "sprite": "rv_mat_egg", "placeholder": true,
		"lore": "Too big for a hen, too warm for a rock. The farmer is not asking follow-up questions."},
	"rv_mat_mushroom_teal": {"group": "supplies", "name": "Glowcap", "sprite": "rv_mat_mushroom_teal", "placeholder": true,
		"lore": "Teal light, no heat. Miners plant them at junctions and thank them out loud."},
	"rv_mat_root": {"group": "supplies", "name": "Twisted Root", "sprite": "rv_mat_root", "placeholder": true,
		"lore": "Pulled whole from under a gallows-oak. Bitter tea, strong medicine, bad dreams."},
	"rv_mat_mushroom_red": {"group": "supplies", "name": "Crimson Cap", "sprite": "rv_mat_mushroom_red", "placeholder": true,
		"lore": "Bright as a warning, because it is one. Cooks it kills learn nothing; cooks it spares learn ratios."},
	"rv_mat_frond": {"group": "supplies", "name": "Crimson Frond", "sprite": "rv_mat_frond", "placeholder": true,
		"lore": "A fern the color of an open wound. It grows where the ground remembers something."},
	"rv_mat_coral": {"group": "supplies", "name": "Blood Coral", "sprite": "rv_mat_coral", "placeholder": true,
		"lore": "Branching red stone from water no one fishes twice. Sells by the ounce, inland."},
	"rv_tool_mortar": {"group": "supplies", "name": "Mortar & Pestle", "sprite": "rv_tool_mortar", "placeholder": true,
		"lore": "Granite bowl, worn hollow. Everything medicine starts as something ground down."},
	"rv_tool_scales": {"group": "supplies", "name": "Merchant's Scales", "sprite": "rv_tool_scales", "placeholder": true,
		"lore": "Brass pans, honest pivot. The thumb on the left pan is a rumor and a slander."},
	"rv_tool_anvil": {"group": "supplies", "name": "Smith's Anvil", "sprite": "rv_tool_anvil", "placeholder": true,
		"lore": "The town's oldest resident, and the only one that never complains about the noise."},
	"rv_tool_rod": {"group": "supplies", "name": "Fishing Rod", "sprite": "rv_tool_rod", "placeholder": true,
		"lore": "Cane, cord, hook, patience. Three of the four are replaceable."},
	"rv_tool_bait": {"group": "supplies", "name": "Bait Bucket", "sprite": "rv_tool_bait", "placeholder": true,
		"lore": "Do not look inside. The fish will, and that is the entire arrangement."},
	"rv_mat_pearl": {"group": "supplies", "name": "Pearl", "sprite": "rv_mat_pearl", "placeholder": true,
		"lore": "An oyster's grudge, worn as jewelry. The sea's patience, priced by the carat."},
	"rv_mat_pearl_gold": {"group": "supplies", "name": "Golden Pearl", "sprite": "rv_mat_pearl_gold", "placeholder": true,
		"lore": "One in ten thousand shells. Divers who find one retire; divers who brag about one drown."},
	# ---- PROVISIONS (the Raven pantry — future cooking consumables).
	"rv_food_strawberry": {"group": "provisions", "name": "Strawberry", "sprite": "rv_food_strawberry", "placeholder": true,
		"lore": "Summer in one bite, seeds and all."},
	"rv_food_apple": {"group": "provisions", "name": "Apple", "sprite": "rv_food_apple", "placeholder": true,
		"lore": "Red, crisp, and endlessly implicated in mythology. Eat it anyway."},
	"rv_food_cherry": {"group": "provisions", "name": "Cherries", "sprite": "rv_food_cherry", "placeholder": true,
		"lore": "Two to a stem, like they know something."},
	"rv_food_onion": {"group": "provisions", "name": "Onion", "sprite": "rv_food_onion", "placeholder": true,
		"lore": "Layers, tears, and the base of every soup worth the name."},
	"rv_food_carrot": {"group": "provisions", "name": "Carrot", "sprite": "rv_food_carrot", "placeholder": true,
		"lore": "Pulled fresh, greens and all. Horses will forgive you anything for one."},
	"rv_food_potato": {"group": "provisions", "name": "Potato", "sprite": "rv_food_potato", "placeholder": true,
		"lore": "The field's plain miracle. Boil it, mash it — the joke writes itself and stays true."},
	"rv_food_grapes": {"group": "provisions", "name": "Grapes", "sprite": "rv_food_grapes", "placeholder": true,
		"lore": "Eaten now: a snack. Waited on: an industry."},
	"rv_food_melon": {"group": "provisions", "name": "Melon", "sprite": "rv_food_melon", "placeholder": true,
		"lore": "Green rind, red promise. Thumped knowingly by people who cannot explain what they are listening for."},
	"rv_food_pumpkin": {"group": "provisions", "name": "Pumpkin", "sprite": "rv_food_pumpkin", "placeholder": true,
		"lore": "Autumn's cannonball. Soup, pie, or lantern — it retires well."},
	"rv_food_corn": {"group": "provisions", "name": "Corn Cob", "sprite": "rv_food_corn", "placeholder": true,
		"lore": "Gold you can grow. The husk keeps the secret until supper."},
	"rv_food_meatcut": {"group": "provisions", "name": "Cut of Meat", "sprite": "rv_food_meatcut", "placeholder": true,
		"lore": "Butcher's red, marbled white. The stew's opening argument."},
	"rv_food_bacon": {"group": "provisions", "name": "Bacon Strips", "sprite": "rv_food_bacon", "placeholder": true,
		"lore": "The smell that empties bunkhouses. Negotiations improve downwind of it."},
	"rv_food_sausage": {"group": "provisions", "name": "Sausage", "sprite": "rv_food_sausage", "placeholder": true,
		"lore": "Cased confidence. The butcher's word is the only ingredient list."},
	"rv_food_drumstick": {"group": "provisions", "name": "Drumstick", "sprite": "rv_food_drumstick", "placeholder": true,
		"lore": "The cut with a handle. Feasts were invented around it."},
	"rv_food_fillet": {"group": "provisions", "name": "Salmon Fillet", "sprite": "rv_food_fillet", "placeholder": true,
		"lore": "Pink, clean, and upstream-earned."},
	"rv_food_steak": {"group": "provisions", "name": "Smoked Steak", "sprite": "rv_food_steak", "placeholder": true,
		"lore": "Dark bark, red heart. Smoke did most of the cooking and takes most of the credit."},
	"rv_food_cheese": {"group": "provisions", "name": "Wedge of Cheese", "sprite": "rv_food_cheese", "placeholder": true,
		"lore": "Aged in a cave by someone patient. The holes are flavor that got away."},
	"rv_food_ale": {"group": "provisions", "name": "Mug of Ale", "sprite": "rv_food_ale", "placeholder": true,
		"lore": "Foam on top, courage underneath. The village's other currency."},
	"rv_food_tea": {"group": "provisions", "name": "Cup of Tea", "sprite": "rv_food_tea", "placeholder": true,
		"lore": "Steeped dark and taken seriously. Wars have paused for less."},
	"rv_food_preserves": {"group": "provisions", "name": "Jar of Preserves", "sprite": "rv_food_preserves", "placeholder": true,
		"lore": "Berries argued into permanence. Winter opens it like a letter from summer."},
	"rv_food_loaf": {"group": "provisions", "name": "Fresh Loaf", "sprite": "rv_food_loaf", "placeholder": true,
		"lore": "Crust that crackles, crumb that steams. The baker's daily proof of good in the world."},
	"rv_food_croissant": {"group": "provisions", "name": "Croissant", "sprite": "rv_food_croissant", "placeholder": true,
		"lore": "Butter, folded seventeen times, wearing a pastry disguise."},
	"rv_food_cupcake": {"group": "provisions", "name": "Cupcake", "sprite": "rv_food_cupcake", "placeholder": true,
		"lore": "A celebration scaled to one person. Frosted accordingly."},
	"rv_food_cookie": {"group": "provisions", "name": "Cookie", "sprite": "rv_food_cookie", "placeholder": true,
		"lore": "Baked by the dozen, missing by the half-dozen. The tin lies."},
	"rv_food_cream": {"group": "provisions", "name": "Cream Jug", "sprite": "rv_food_cream", "placeholder": true,
		"lore": "Top of the milk, pride of the dairy. Cats organize around it."},
	"rv_food_pizza": {"group": "provisions", "name": "Flatbread Pie", "sprite": "rv_food_pizza", "placeholder": true,
		"lore": "Bread, sauce, cheese, fire. Four ingredients, zero complaints."},
	"rv_food_donut": {"group": "provisions", "name": "Glazed Ring", "sprite": "rv_food_donut", "placeholder": true,
		"lore": "Pink-iced and improbable. The hole is a tax."},
	"rv_food_pie": {"group": "provisions", "name": "Berry Pie", "sprite": "rv_food_pie", "placeholder": true,
		"lore": "Lattice top, purple evidence underneath. Windowsills are not secure storage."},
	"rv_food_honey": {"group": "provisions", "name": "Honey Jar", "sprite": "rv_food_honey", "placeholder": true,
		"lore": "The only food that never spoils, hoarded by the only insect that unionized."},
	"rv_food_sandwich": {"group": "provisions", "name": "Sandwich", "sprite": "rv_food_sandwich", "placeholder": true,
		"lore": "Everything good, stacked, portable. Civilization's quiet peak."},
	"rv_food_goldpie": {"group": "provisions", "name": "Golden Pie", "sprite": "rv_food_goldpie", "placeholder": true,
		"lore": "Egg-washed to a shine. Contest winner three fairs running; recipe goes to the grave."},
	"rv_food_stew": {"group": "provisions", "name": "Hearty Stew", "sprite": "rv_food_stew", "placeholder": true,
		"lore": "Everything the week left over, simmered into agreement."},
	"rv_food_spice_green": {"group": "provisions", "name": "Green Spice Bowl", "sprite": "rv_food_spice_green", "placeholder": true,
		"lore": "Ground herbs from the coast road. A pinch wakes the pot up."},
	"rv_food_spice_red": {"group": "provisions", "name": "Red Spice Bowl", "sprite": "rv_food_spice_red", "placeholder": true,
		"lore": "Sold by weight, handled with respect. The caravans call it edible fire."},
	"rv_food_sushi": {"group": "provisions", "name": "Fish Roll", "sprite": "rv_food_sushi", "placeholder": true,
		"lore": "Rice, fish, seaweed, discipline. Coastal cooking at its most exact."},
	"rv_food_fish": {"group": "provisions", "name": "Fresh Catch", "sprite": "rv_food_fish", "placeholder": true,
		"lore": "Silver-blue and still surprised. Dinner, an hour off the hook."},
	# ---- CRITTERS (Ninja Adventure animals — livestock & wildlife for the
	# living world: village pens, farm fields, wild zones. Promotion path:
	# ambient spawns / farm dressing / hunt-quest targets).
	"na_chicken": {"group": "critters", "name": "Copper Hen", "sprite": "chicken", "placeholder": true,
		"lore": "Scratches, complains, lays. The village alarm nobody asked for and everybody relies on."},
	"na_cow": {"group": "critters", "name": "Dapple Cow", "sprite": "cow", "placeholder": true,
		"lore": "Slow, certain, and the whole economy of three families."},
	"na_pig": {"group": "critters", "name": "Pink Sow", "sprite": "pig", "placeholder": true,
		"lore": "Eats anything, forgives everything. The farm's round pink optimist."},
	"na_horse": {"group": "critters", "name": "Bay Courser", "sprite": "horse", "placeholder": true,
		"lore": "Four beats to a gallop, and the road is suddenly half as long."},
	"na_dog": {"group": "critters", "name": "Farm Hound", "sprite": "dog", "placeholder": true,
		"lore": "Knows the flock, the fence line, and exactly one trick. Loyal past all argument."},
	"na_cat": {"group": "critters", "name": "Barn Cat", "sprite": "cat", "placeholder": true,
		"lore": "Employed by the granary, answerable to no one. Rent is paid in mice."},
	"na_boar": {"group": "critters", "name": "Russet Boar", "sprite": "boar", "placeholder": true,
		"lore": "Tusks first, questions never. Hunters speak of it in the plural, respectfully."},
	"na_racoon": {"group": "critters", "name": "Masked Thief", "sprite": "racoon", "placeholder": true,
		"lore": "Wears the mask, does the crime. Latches were invented because of this animal."},
	"na_frog": {"group": "critters", "name": "Pond Frog", "sprite": "frog", "placeholder": true,
		"lore": "Sits, watches, judges. The pond's oldest committee of one."},
	"na_monkey": {"group": "critters", "name": "Rust Monkey", "sprite": "monkey", "placeholder": true,
		"lore": "Quick hands, long tail, no shame. Market stalls post lookouts for it."},
	"na_parrot": {"group": "critters", "name": "Scarlet Parrot", "sprite": "parrot", "placeholder": true,
		"lore": "Repeats everything, understands enough. Sailors' secrets die with the ship, not the bird."},
	"na_hyena": {"group": "critters", "name": "Gravel Hyena", "sprite": "hyena", "placeholder": true,
		"lore": "Laughs at its own jokes in the dark past the firelight. Travel in pairs."},
	"na_lion": {"group": "critters", "name": "Dune Lion", "sprite": "lion", "placeholder": true,
		"lore": "Prowls low, mane like a stormcloud. The desert's one opinion on trespass."},
}


## Merge + resolution check: every curio grantable, every icon/sprite
## resolves to installed art. Wall-clock-free.
static func selftest(_game: Node2D) -> String:
	for id in QUEST_ITEMS:
		if not Story.ALL_QUEST_ITEMS.has(id):
			return "rv_na_gallery: quest item %s not merged" % id
		var item := Items.make_quest_item(String(id))
		if item.is_empty() or item.get("kind", "") != "quest":
			return "rv_na_gallery: make_quest_item(%s) did not build a bag rider" % id
		if Art.tex(String(QUEST_ITEMS[id]["icon"])) == null:
			return "rv_na_gallery: icon %s missing" % QUEST_ITEMS[id]["icon"]
	for id in RELICS:
		if not Story.ALL_RELICS.has(id):
			return "rv_na_gallery: relic %s not merged" % id
		if Art.tex(String(RELICS[id]["sprite"])) == null:
			return "rv_na_gallery: relic sprite %s missing" % RELICS[id]["sprite"]
	# critters also ship a 2-frame _anim strip — verify those resolve too
	for id in RELICS:
		if String(RELICS[id].get("group", "")) == "critters":
			if Art.tex(String(RELICS[id]["sprite"]) + "_anim") == null:
				return "rv_na_gallery: critter strip %s_anim missing" % RELICS[id]["sprite"]
	return ""
